! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : mozart_Monitor.f90
! Time                 : Mon Sep 26 23:37:16 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/mozart
! Equation file        : mozart.kpp
! Output root filename : mozart
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mozart_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(83) :: SPC_NAMES = (/ &
     'SO4         ','NH3         ','N2O         ', &
     'C2H6        ','C3H8        ','BIGENE      ', &
     'BIGALK      ','SO2         ','H2O2        ', &
     'TOLUENE     ','CRESOL      ','EO          ', &
     'N2O5        ','XOH         ','XOOH        ', &
     'DMS         ','C2H5OH      ','CH3OOH      ', &
     'H2          ','MACROOH     ','C2H5OOH     ', &
     'C3H7OOH     ','ROOH        ','ENEO2       ', &
     'MEKOOH      ','HO2NO2      ','C2H4        ', &
     'HYDRALD     ','ONIT        ','EO2         ', &
     'TOLOOH      ','CH3COOOH    ','MEK         ', &
     'CH3COOH     ','POOH        ','PAN         ', &
     'GLYOXAL     ','TERPOOH     ','HNO3        ', &
     'CH4         ','CH3OH       ','ISOPOOH     ', &
     'MPAN        ','TOLO2       ','BIGALD      ', &
     'C10H16      ','O1D_CB4     ','ALKOOH      ', &
     'MEKO2       ','PO2         ','CH3COCH3    ', &
     'O           ','GLYALD      ','ALKO2       ', &
     'C2H5O2      ','ISOPNO3     ','C3H7O2      ', &
     'CO          ','ISOP        ','ONITR       ', &
     'C3H6        ','CH3CHO      ','RO2         ', &
     'TERPO2      ','HYAC        ','MACR        ', &
     'CH3COCHO    ','XO2         ','MVK         ', &
     'MACRO2      ','ISOPO2      ','CH2O        ', &
     'NO2         ','MCO3        ','OH          ', &
     'NO          ','CH3O2       ','CH3CO3      ', &
     'HO2         ','NO3         ','O3          ', &
     'H2O         ','M           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '                    M --> 6.95284e-31 O                                                             ', &
     '                   O3 --> O1D_CB4                                                                   ', &
     '                   O3 --> O                                                                         ', &
     '                  N2O --> O1D_CB4                                                                   ', &
     '                  NO2 --> O + NO                                                                    ', &
     '                 N2O5 --> NO2 + NO3                                                                 ', &
     '                 HNO3 --> NO2 + OH                                                                  ', &
     '                  NO3 --> 6.95284e-31 NO2 + 6.95284e-31 NO + 6.95284e-31 O3                         ', &
     '               HO2NO2 --> 6.95284e-31 NO2 + 6.95284e-31 OH + 6.95284e-31 HO2 + 6.95284e-31 NO3      ', &
     '               CH3OOH --> CH2O + OH + HO2                                                           ', &
     '                 CH2O --> CO + 6.95284e-31 HO2                                                      ', &
     '                 CH2O --> H2 + CO                                                                   ', &
     '                 H2O2 --> 6.95284e-31 OH                                                            ', &
     '               CH3CHO --> CO + CH3O2 + HO2                                                          ', &
     '                 POOH --> CH3CHO + CH2O + OH + HO2                                                  ', &
     '             CH3COOOH --> OH + CH3O2                                                                ', &
     '                  PAN --> 6.95284e-31 NO2 + 6.95284e-31 CH3O2 + 6.95284e-31 CH3CO3 + 6.95284e-31 NO3', &
     '                 MPAN --> NO2 + MCO3                                                                ', &
     '                 MACR --> 6.95284e-31 CO + 6.95284e-31 CH2O + 6.95284e-31 MCO3 + 6.95284e-31 OH + 6.', &
     '                  MVK --> 6.95284e-31 CO + 6.95284e-31 C3H6 + 6.95284e-31 CH3O2 + 6.95284e-31 CH3CO3', &
     '              C2H5OOH --> CH3CHO + OH + HO2                                                         ', &
     '              C3H7OOH --> 6.95284e-31 CH3COCH3 + OH + HO2                                           ', &
     '                 ROOH --> CH2O + OH + CH3CO3                                                        ', &
     '             CH3COCH3 --> CH3O2 + CH3CO3                                                            ', &
     '             CH3COCHO --> CO + CH3CO3 + HO2                                                         ', &
     '                 XOOH --> OH                                                                        ', &
     '                ONITR --> CO + CH2O + NO2 + HO2                                                     ', &
     '              ISOPOOH --> 6.95284e-31 MACR + 6.95284e-31 MVK + 6.95284e-31 CH2O + HO2               ', &
     '                 HYAC --> CH2O + CH3CO3 + HO2                                                       ', &
     '               GLYALD --> CO + CH2O + 6.95284e-31 HO2                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '                  MEK --> C2H5O2 + CH3CO3                                                           ', &
     '               BIGALD --> 6.95284e-31 GLYOXAL + 6.95284e-31 CO + 6.95284e-31 CH3COCHO + 6.95284e-31 ', &
     '              GLYOXAL --> 6.95284e-31 CO + 6.95284e-31 HO2                                          ', &
     '               ALKOOH --> 6.95284e-31 MEK + 6.95284e-31 CH3COCH3 + 6.95284e-31 CH3CHO + 6.95284e-31 ', &
     '               MEKOOH --> CH3CHO + OH + CH3CO3                                                      ', &
     '               TOLOOH --> 6.95284e-31 GLYOXAL + 6.95284e-31 BIGALD + 6.95284e-31 CH3COCHO + OH      ', &
     '              TERPOOH --> 6.95284e-31 CH3COCH3 + MACR + MVK + OH + HO2                              ', &
     '                O + M --> O3                                                                        ', &
     '               O + O3 --> M                                                                         ', &
     '          O1D_CB4 + M --> O                                                                         ', &
     '        O1D_CB4 + H2O --> 6.95284e-31 OH                                                            ', &
     '         H2 + O1D_CB4 --> OH + HO2                                                                  ', &
     '              H2 + OH --> HO2 + H2O                                                                 ', &
     '               O + OH --> HO2                                                                       ', &
     '              O + HO2 --> OH                                                                        ', &
     '              OH + O3 --> HO2                                                                       ', &
     '             HO2 + O3 --> OH                                                                        ', &
     '6.95284e-31 HO2 + H2O --> H2O2                                                                      ', &
     '            H2O2 + OH --> HO2 + H2O                                                                 ', &
     '             OH + HO2 --> H2O                                                                       ', &
     '       6.95284e-31 OH --> O + H2O                                                                   ', &
     '       6.95284e-31 OH --> H2O2                                                                      ', &
     '        N2O + O1D_CB4 --> 6.95284e-31 NO                                                            ', &
     '        N2O + O1D_CB4 --> M                                                                         ', &
     '             NO + HO2 --> NO2 + OH                                                                  ', &
     '              NO + O3 --> NO2                                                                       ', &
     '              O + NO2 --> NO                                                                        ', &
     '             NO2 + O3 --> NO3                                                                       ', &
     '            HO2 + NO3 --> NO2 + OH                                                                  ', &
     '            NO2 + NO3 --> N2O5                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '                 N2O5 --> NO2 + NO3                                                                 ', &
     '             NO2 + OH --> HNO3                                                                      ', &
     '            HNO3 + OH --> NO3 + H2O                                                                 ', &
     '             NO + NO3 --> 6.95284e-31 NO2                                                           ', &
     '            NO2 + HO2 --> HO2NO2                                                                    ', &
     '          HO2NO2 + OH --> NO2 + H2O                                                                 ', &
     '               HO2NO2 --> NO2 + HO2                                                                 ', &
     '             N2O5 + M --> 6.95284e-31 HNO3                                                          ', &
     '                  NO3 --> HNO3                                                                      ', &
     '                  NO2 --> 6.95284e-31 HNO3 + 6.95284e-31 OH + 6.95284e-31 NO                        ', &
     '             CH4 + OH --> CH3O2 + H2O                                                               ', &
     '        CH4 + O1D_CB4 --> 6.95284e-31 H2 + 6.95284e-31 CH2O + 6.95284e-31 OH + 6.95284e-31 CH3O2 + 6', &
     '           NO + CH3O2 --> CH2O + NO2 + HO2                                                          ', &
     '    6.95284e-31 CH3O2 --> 6.95284e-31 CH2O + 6.95284e-31 HO2                                        ', &
     '    6.95284e-31 CH3O2 --> CH3OH + CH2O                                                              ', &
     '          CH3O2 + HO2 --> CH3OOH                                                                    ', &
     '          CH3OOH + OH --> 6.95284e-31 CH2O + 6.95284e-31 OH + 6.95284e-31 CH3O2 + H2O               ', &
     '           CH2O + NO3 --> HNO3 + CO + HO2                                                           ', &
     '            CH2O + OH --> CO + HO2 + H2O                                                            ', &
     '              CO + OH --> HO2                                                                       ', &
     '            C2H4 + OH --> 6.95284e-31 EO2 + 6.95284e-31 CH2O + 6.95284e-31 HO2                      ', &
     '            C2H4 + O3 --> 6.95284e-31 CH3COOH + 6.95284e-31 CO + CH2O + 6.95284e-31 OH + 6.95284e-31', &
     '             SO2 + OH --> SO4                                                                       ', &
     '         GLYOXAL + OH --> CO + HO2                                                                  ', &
     '             EO2 + NO --> EO + NO2                                                                  ', &
     '               EO + M --> GLYALD + HO2                                                              ', &
     '                   EO --> 6.95284e-31 CH2O + HO2                                                    ', &
     '            C2H6 + OH --> C2H5O2                                                                    ', &
     '          C2H5O2 + NO --> CH3CHO + NO2 + HO2                                                        ', &
     '         C2H5O2 + HO2 --> C2H5OOH                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '       C2H5O2 + CH3O2 --> 6.95284e-31 C2H5OH + 6.95284e-31 CH3OH + 6.95284e-31 CH3CHO + 6.95284e-31 ', &
     '         C2H5OOH + OH --> 6.95284e-31 C2H5O2 + 6.95284e-31 CH3CHO + 6.95284e-31 OH                  ', &
     '            C3H6 + OH --> PO2                                                                       ', &
     '            C3H6 + O3 --> 6.95284e-31 CH3COOH + 6.95284e-31 CH4 + 6.95284e-31 CO + 6.95284e-31 CH3CH', &
     '           C3H6 + NO3 --> ONIT                                                                      ', &
     '             PO2 + NO --> CH3CHO + CH2O + NO2 + HO2                                                 ', &
     '            PO2 + HO2 --> POOH                                                                      ', &
     '            POOH + OH --> 6.95284e-31 PO2 + 6.95284e-31 HYAC + 6.95284e-31 OH                       ', &
     '          CH3CHO + OH --> CH3CO3                                                                    ', &
     '         CH3CHO + NO3 --> HNO3 + CH3CO3                                                             ', &
     '          NO + CH3CO3 --> NO2 + CH3O2                                                               ', &
     '         NO2 + CH3CO3 --> PAN                                                                       ', &
     '         CH3CO3 + HO2 --> 6.95284e-31 CH3COOOH + 6.95284e-31 CH3COOH + 6.95284e-31 O3               ', &
     '       CH3O2 + CH3CO3 --> 6.95284e-31 CH3COOH + CH2O + 6.95284e-31 CH3O2 + 6.95284e-31 HO2          ', &
     '        CH3COOOH + OH --> 6.95284e-31 CH2O + 6.95284e-31 CH3CO3                                     ', &
     '                  PAN --> NO2 + CH3CO3                                                              ', &
     '   6.95284e-31 CH3CO3 --> 6.95284e-31 CH3O2                                                         ', &
     '            C3H8 + OH --> C3H7O2                                                                    ', &
     '          C3H7O2 + NO --> 6.95284e-31 CH3COCH3 + 6.95284e-31 CH3CHO + NO2 + HO2                     ', &
     '         C3H7O2 + HO2 --> C3H7OOH                                                                   ', &
     '       C3H7O2 + CH3O2 --> 6.95284e-31 CH3COCH3 + CH2O + HO2                                         ', &
     '         C3H7OOH + OH --> C3H7O2                                                                    ', &
     '        CH3COCH3 + OH --> RO2                                                                       ', &
     '             RO2 + NO --> CH2O + NO2 + CH3CO3                                                       ', &
     '            RO2 + HO2 --> ROOH                                                                      ', &
     '          RO2 + CH3O2 --> 6.95284e-31 CH3OH + 6.95284e-31 HYAC + 6.95284e-31 CH3COCHO + 6.95284e-31 ', &
     '            ROOH + OH --> RO2                                                                       ', &
     '          BIGENE + OH --> ENEO2                                                                     ', &
     '           ENEO2 + NO --> 6.95284e-31 CH3COCH3 + CH3CHO + 6.95284e-31 CH2O + NO2 + HO2              ', &
     '          BIGALK + OH --> ALKO2                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '           ALKO2 + NO --> 6.95284e-31 ONIT + 6.95284e-31 MEK + 6.95284e-31 CH3COCH3 + 6.95284e-31 CH', &
     '          ALKO2 + HO2 --> ALKOOH                                                                    ', &
     '          ALKOOH + OH --> ALKO2                                                                     ', &
     '            ONIT + OH --> CH3COCHO + NO2                                                            ', &
     '             MEK + OH --> MEKO2                                                                     ', &
     '           MEKO2 + NO --> CH3CHO + NO2 + CH3CO3                                                     ', &
     '          MEKO2 + HO2 --> MEKOOH                                                                    ', &
     '          MEKOOH + OH --> MEKO2                                                                     ', &
     '         TOLUENE + OH --> 6.95284e-31 CRESOL + 6.95284e-31 TOLO2 + 6.95284e-31 HO2                  ', &
     '          CRESOL + OH --> XOH                                                                       ', &
     '            XOH + NO2 --> 6.95284e-31 BIGALD + 6.95284e-31 NO2 + 6.95284e-31 HO2                    ', &
     '           TOLO2 + NO --> 6.95284e-31 GLYOXAL + 6.95284e-31 BIGALD + 6.95284e-31 CH3COCHO + 6.95284e', &
     '          TOLO2 + HO2 --> TOLOOH                                                                    ', &
     '          TOLOOH + OH --> TOLO2                                                                     ', &
     '            ISOP + OH --> ISOPO2                                                                    ', &
     '            ISOP + O3 --> 6.95284e-31 CH3COOH + 6.95284e-31 CO + 6.95284e-31 C3H6 + 6.95284e-31 MACR', &
     '          ISOPO2 + NO --> 6.95284e-31 HYDRALD + 6.95284e-31 ONITR + 6.95284e-31 MACR + 6.95284e-31 M', &
     '         ISOPO2 + NO3 --> 6.95284e-31 HYDRALD + 6.95284e-31 MACR + 6.95284e-31 MVK + 6.95284e-31 CH2', &
     '         ISOPO2 + HO2 --> ISOPOOH                                                                   ', &
     '         ISOPOOH + OH --> 6.95284e-31 XO2 + 6.95284e-31 ISOPO2                                      ', &
     '       ISOPO2 + CH3O2 --> 6.95284e-31 HYDRALD + 6.95284e-31 CH3OH + 6.95284e-31 MACR + 6.95284e-31 M', &
     '      ISOPO2 + CH3CO3 --> 6.95284e-31 HYDRALD + 6.95284e-31 MACR + 6.95284e-31 MVK + 6.95284e-31 CH2', &
     '             MVK + OH --> MACRO2                                                                    ', &
     '             MVK + O3 --> 6.95284e-31 CO + 6.95284e-31 CH3CHO + 6.95284e-31 CH3COCHO + 6.95284e-31 C', &
     '            MACR + OH --> 6.95284e-31 MACRO2 + 6.95284e-31 MCO3                                     ', &
     '            MACR + O3 --> 6.95284e-31 CO + 6.95284e-31 CH3COCHO + 6.95284e-31 CH2O + 6.95284e-31 OH ', &
     '          MACRO2 + NO --> 6.95284e-31 GLYALD + 6.95284e-31 CO + 6.95284e-31 HYAC + 6.95284e-31 CH3CO', &
     '          MACRO2 + NO --> 6.95284e-31 ONITR                                                         ', &
     '         MACRO2 + NO3 --> 6.95284e-31 GLYALD + 6.95284e-31 CO + 6.95284e-31 HYAC + 6.95284e-31 CH3CO', &
     '         MACRO2 + HO2 --> MACROOH                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '       MACRO2 + CH3O2 --> 6.95284e-31 CH3OH + 6.95284e-31 GLYALD + 6.95284e-31 CO + 6.95284e-31 HYAC', &
     '      MACRO2 + CH3CO3 --> 6.95284e-31 GLYALD + 6.95284e-31 CO + 6.95284e-31 HYAC + 6.95284e-31 CH3CO', &
     '         MACROOH + OH --> 6.95284e-31 MACRO2 + 6.95284e-31 MCO3 + 6.95284e-31 OH + 6.95284e-31 HO2  ', &
     '            MCO3 + NO --> CH2O + NO2 + CH3CO3                                                       ', &
     '           MCO3 + NO3 --> CH2O + NO2 + CH3CO3                                                       ', &
     '           MCO3 + HO2 --> 6.95284e-31 CH3COOOH + 6.95284e-31 CH3COOH + 6.95284e-31 O3               ', &
     '         MCO3 + CH3O2 --> 6.95284e-31 CH2O + CH3CO3 + HO2                                           ', &
     '        MCO3 + CH3CO3 --> CH2O + CH3O2 + CH3CO3                                                     ', &
     '     6.95284e-31 MCO3 --> 6.95284e-31 CH2O + 6.95284e-31 CH3CO3                                     ', &
     '       NO2 + MCO3 + M --> MPAN                                                                      ', &
     '             MPAN + M --> NO2 + MCO3                                                                ', &
     '          C10H16 + OH --> TERPO2                                                                    ', &
     '          C10H16 + O3 --> MACR + MVK + 6.95284e-31 OH + HO2                                         ', &
     '         C10H16 + NO3 --> TERPO2 + NO2                                                              ', &
     '          TERPO2 + NO --> 6.95284e-31 CH3COCH3 + MACR + MVK + NO2 + HO2                             ', &
     '         TERPO2 + HO2 --> TERPOOH                                                                   ', &
     '         TERPOOH + OH --> TERPO2                                                                    ', &
     '         CH3COOH + OH --> CH3O2                                                                     ', &
     '           ISOP + NO3 --> ISOPNO3                                                                   ', &
     '         ISOPNO3 + NO --> 6.95284e-31 ONITR + 6.95284e-31 MACR + 6.95284e-31 MVK + 6.95284e-31 CH2O ', &
     '        ISOPNO3 + NO3 --> 6.95284e-31 ONITR + 6.95284e-31 MACR + 6.95284e-31 MVK + 6.95284e-31 CH2O ', &
     '        ISOPNO3 + HO2 --> 6.95284e-31 ONITR + 6.95284e-31 MACR + 6.95284e-31 MVK + 6.95284e-31 CH2O ', &
     '        CH3COCHO + OH --> CO + CH3CO3                                                               ', &
     '       CH3COCHO + NO3 --> HNO3 + CO + CH3CO3                                                        ', &
     '           ONITR + OH --> HYDRALD + 6.95284e-31 NO2 + HO2                                           ', &
     '          ONITR + NO3 --> HYDRALD + NO2 + HO2                                                       ', &
     '         HYDRALD + OH --> XO2                                                                       ', &
     '             XO2 + NO --> 6.95284e-31 GLYALD + CO + 6.95284e-31 HYAC + 6.95284e-31 CH3COCHO + NO2 + ', &
     '            XO2 + NO3 --> 6.95284e-31 GLYALD + CO + 6.95284e-31 HYAC + 6.95284e-31 CH3COCHO + NO2 + ', &
     '            XO2 + HO2 --> XOOH                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(16) :: EQN_NAMES_6 = (/ &
     '          XO2 + CH3O2 --> 6.95284e-31 CH3OH + 6.95284e-31 GLYALD + 6.95284e-31 CO + 6.95284e-31 HYAC', &
     '         XO2 + CH3CO3 --> 6.95284e-31 GLYALD + CO + 6.95284e-31 HYAC + 6.95284e-31 CH3COCHO + CH3O2 ', &
     '            XOOH + OH --> XO2                                                                       ', &
     '            XOOH + OH --> OH                                                                        ', &
     '           CH3OH + OH --> CH2O + HO2                                                                ', &
     '          C2H5OH + OH --> CH3CHO + HO2                                                              ', &
     '            MPAN + OH --> 6.95284e-31 HYAC + 6.95284e-31 CH2O + 6.95284e-31 HO2 + 6.95284e-31 NO3   ', &
     '             PAN + OH --> CH2O + NO3                                                                ', &
     '            HYAC + OH --> CH3COCHO + HO2                                                            ', &
     '          GLYALD + OH --> 6.95284e-31 GLYOXAL + 6.95284e-31 CH2O + HO2                              ', &
     '             DMS + OH --> SO2                                                                       ', &
     '             DMS + OH --> 6.95284e-31 SO2 + 6.95284e-31 HO2                                         ', &
     '            DMS + NO3 --> SO2 + HNO3                                                                ', &
     '             NH3 + OH --> M                                                                         ', &
     '                  HO2 --> 6.95284e-31 H2O2                                                          ', &
     '   6.95284e-31 C2H5O2 --> 6.95284e-31 C2H5OH + 6.95284e-31 CH3CHO + 6.95284e-31 HO2                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(196) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6 /)

! INLINED global variables

! End INLINED global variables


END MODULE mozart_Monitor
