! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : t1_mozcart_Monitor.f90
! Time                 : Mon Sep 26 23:37:56 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/t1_mozcart
! Equation file        : t1_mozcart.kpp
! Output root filename : t1_mozcart
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE t1_mozcart_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'SO4         ','NH3         ','C2H6        ', &
     'C3H8        ','CH3CN       ','N2O         ', &
     'SO2         ','EOOH        ','IEPOX       ', &
     'PBZNIT      ','C2H2        ','BENZENE     ', &
     'BEPOMUC     ','PHENOL      ','HCN         ', &
     'N2O5        ','TOLUENE     ','CRESOL      ', &
     'TEPOMUC     ','XOOH        ','XYLENES     ', &
     'XYLOL       ','DMS         ','HPALD       ', &
     'BZALD       ','ONITR       ','H2O2        ', &
     'C6H5OOH     ','C2H5OH      ','EO          ', &
     'BIGALD2     ','CH3OOH      ','HO2NO2      ', &
     'C3H7OOH     ','HYDRALD     ','MACROOH     ', &
     'MEKOOH      ','PHENOOH     ','ROOH        ', &
     'BZOOH       ','BIGALD4     ','C2H5OOH     ', &
     'CH3COOH     ','BIGENE      ','BIGALK      ', &
     'C2H4        ','ISOPNOOH    ','BENZOOH     ', &
     'NC4CH2OH    ','NTERPOOH    ','XYLOLOOH    ', &
     'BZOO        ','HOCH2OO     ','PHENO2      ', &
     'BIGALD1     ','CH3COOOH    ','PAN         ', &
     'PHENO       ','POOH        ','TERPOOH     ', &
     'BENZO2      ','XYLOLO2     ','MEK         ', &
     'HMPROPO2    ','ACBZO2      ','H2          ', &
     'MBOOOH      ','MPAN        ','ISOPNITB    ', &
     'ENEO2       ','CH4         ','ISOPNITA    ', &
     'BIGALD3     ','TERP2OOH    ','EO2         ', &
     'TERPNIT     ','C6H5O2      ','ALKOOH      ', &
     'TOLOOH      ','ALKNIT      ','MEKO2       ', &
     'PO2         ','HCOOH       ','BIGALD      ', &
     'XYLENOOH    ','MALO2       ','TOLO2       ', &
     'ISOPOOH     ','MBO         ','XYLENO2     ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(57) :: SPC_NAMES_1 = (/ &
     'DICARBO2    ','C3H7O2      ','O1D         ', &
     'CH3OH       ','C2H5O2      ','MBONO3O2    ', &
     'HMPROP      ','ISOP        ','NOA         ', &
     'BCARY       ','APIN        ','GLYOXAL     ', &
     'MDIALO2     ','BPIN        ','MYRC        ', &
     'LIMON       ','ALKO2       ','CH3COCH3    ', &
     'CO          ','GLYALD      ','MBOO2       ', &
     'TERPROD2    ','HNO3        ','C3H6        ', &
     'CH3CHO      ','TERP2O2     ','NC4CHO      ', &
     'NTERPO2     ','TERPO2      ','TERPROD1    ', &
     'RO2         ','O           ','HYAC        ', &
     'HONITR      ','MACRO2      ','CH3COCHO    ', &
     'XO2         ','ISOPAO2     ','ISOPNO3     ', &
     'ISOPBO2     ','MACR        ','CH2O        ', &
     'MVK         ','NO3         ','O3          ', &
     'CH3CO3      ','NO2         ','OH          ', &
     'MCO3        ','CH3O2       ','HO2         ', &
     'NO          ','M           ','H2O         ', &
     'O2          ','N2          ','CO2         ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(147) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '              H2O2 --> 6.95266e-31 OH                                                               ', &
     '                O2 --> 6.95266e-31 O                                                                ', &
     '                O3 --> O + O2                                                                       ', &
     '                O3 --> O1D + O2                                                                     ', &
     '              HNO3 --> NO2 + OH                                                                     ', &
     '            HO2NO2 --> 6.95266e-31 NO3 + 6.95266e-31 NO2 + 6.95266e-31 OH + 6.95266e-31 HO2         ', &
     '               N2O --> O1D + N2                                                                     ', &
     '              N2O5 --> NO3 + NO2                                                                    ', &
     '               NO2 --> O + NO                                                                       ', &
     '               NO3 --> 6.95266e-31 O3 + 6.95266e-31 NO2 + 6.95266e-31 NO                            ', &
     '            ALKNIT --> 6.95266e-31 MEK + 6.95266e-31 CH3COCH3 + 6.95266e-31 CH3CHO + 6.95266e-31 CH2', &
     '            ALKOOH --> 6.95266e-31 MEK + 6.95266e-31 CH3COCH3 + 6.95266e-31 CH3CHO + 6.95266e-31 CH2', &
     '           BENZOOH --> 6.95266e-31 BIGALD1 + GLYOXAL + OH + HO2                                     ', &
     '           BEPOMUC --> BIGALD1 + 6.95266e-31 CO + 6.95266e-31 HO2                                   ', &
     '            BIGALD --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 CH3COCHO + 6.95266e-31 CH3', &
     '           BIGALD1 --> 6.95266e-31 MALO2 + HO2                                                      ', &
     '           BIGALD2 --> 6.95266e-31 DICARBO2 + 6.95266e-31 HO2                                       ', &
     '           BIGALD3 --> 6.95266e-31 MDIALO2 + 6.95266e-31 CO + 6.95266e-31 HO2                       ', &
     '           BIGALD4 --> CO + CH3COCHO + CH3CO3 + HO2                                                 ', &
     '             BZOOH --> BZALD + OH + HO2                                                             ', &
     '           C2H5OOH --> CH3CHO + OH + HO2                                                            ', &
     '           C3H7OOH --> 6.95266e-31 CH3COCH3 + OH + HO2                                              ', &
     '           C6H5OOH --> PHENO + OH                                                                   ', &
     '              CH2O --> CO + 6.95266e-31 HO2                                                         ', &
     '              CH2O --> H2 + CO                                                                      ', &
     '            CH3CHO --> CO + CH3O2 + HO2                                                             ', &
     '          CH3COCH3 --> CH3CO3 + CH3O2                                                               ', &
     '          CH3COCHO --> CO + CH3CO3 + HO2                                                            ', &
     '          CH3COOOH --> OH + CH3O2 + CO2                                                             ', &
     '            CH3OOH --> CH2O + OH + HO2                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '              EOOH --> EO + OH                                                                      ', &
     '            GLYALD --> CO + CH2O + 6.95266e-31 HO2                                                  ', &
     '           GLYOXAL --> 6.95266e-31 CO + 6.95266e-31 HO2                                             ', &
     '            HMPROP --> CH3COCH3 + CO + 6.95266e-31 HO2                                              ', &
     '            HONITR --> 6.95266e-31 CH3COCH3 + 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 CH3C', &
     '             HPALD --> BIGALD3 + OH + HO2                                                           ', &
     '              HYAC --> CH2O + CH3CO3 + HO2                                                          ', &
     '          ISOPNOOH --> ISOPOOH + NO2 + HO2                                                          ', &
     '           ISOPOOH --> 6.95266e-31 MACR + 6.95266e-31 CH2O + 6.95266e-31 MVK + HO2                  ', &
     '              MACR --> 6.95266e-31 CO + 6.95266e-31 CH2O + 6.95266e-31 CH3CO3 + 6.95266e-31 OH + 6.9', &
     '            MBOOOH --> 6.95266e-31 HMPROP + 6.95266e-31 CH3COCH3 + 6.95266e-31 GLYALD + 6.95266e-31 ', &
     '               MEK --> C2H5O2 + CH3CO3                                                              ', &
     '            MEKOOH --> CH3CHO + CH3CO3 + OH                                                         ', &
     '              MPAN --> NO2 + MCO3                                                                   ', &
     '               MVK --> 6.95266e-31 CO + 6.95266e-31 C3H6 + 6.95266e-31 CH3CO3 + 6.95266e-31 CH3O2   ', &
     '            NC4CHO --> BIGALD3 + NO2 + HO2                                                          ', &
     '               NOA --> CH2O + CH3CO3 + NO2                                                          ', &
     '          NTERPOOH --> TERPROD1 + NO2 + OH                                                          ', &
     '             ONITR --> NO2                                                                          ', &
     '               PAN --> 6.95266e-31 NO3 + 6.95266e-31 CH3CO3 + 6.95266e-31 NO2 + 6.95266e-31 CH3O2 + ', &
     '           PHENOOH --> 6.95266e-31 GLYOXAL + OH + HO2                                               ', &
     '              POOH --> CH3CHO + CH2O + OH + HO2                                                     ', &
     '              ROOH --> CH2O + CH3CO3 + OH                                                           ', &
     '           TEPOMUC --> 6.95266e-31 CO + 6.95266e-31 CH3CO3 + HO2                                    ', &
     '          TERP2OOH --> 6.95266e-31 CH3COCH3 + 6.95266e-31 CO + 6.95266e-31 GLYALD + TERPROD2 + 6.952', &
     '           TERPNIT --> TERPROD1 + NO2 + HO2                                                         ', &
     '           TERPOOH --> 6.95266e-31 CH3COCH3 + TERPROD1 + 6.95266e-31 CH2O + OH + HO2                ', &
     '          TERPROD1 --> CO + TERPROD2 + HO2                                                          ', &
     '          TERPROD2 --> 6.95266e-31 CH3COCH3 + 6.95266e-31 CO + 6.95266e-31 RO2 + 6.95266e-31 CH2O + ', &
     '            TOLOOH --> 6.95266e-31 BIGALD2 + 6.95266e-31 BIGALD1 + 6.95266e-31 BIGALD3 + 6.95266e-31' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '              XOOH --> OH                                                                           ', &
     '          XYLENOOH --> 6.95266e-31 BIGALD2 + 6.95266e-31 BIGALD4 + 6.95266e-31 BIGALD1 + 6.95266e-31', &
     '          XYLOLOOH --> 6.95266e-31 GLYOXAL + 6.95266e-31 CH3COCHO + OH + HO2                        ', &
     '         CH4 + O1D --> 6.95266e-31 H2 + 6.95266e-31 CH2O + 6.95266e-31 OH + 6.95266e-31 CH3O2 + 6.95', &
     '          H2 + O1D --> OH + HO2                                                                     ', &
     '         O1D + H2O --> 6.95266e-31 OH                                                               ', &
     '          O1D + N2 --> O + N2                                                                       ', &
     '          O1D + O2 --> O + O2                                                                       ', &
     '          O1D + O3 --> 6.95266e-31 O2                                                               ', &
     '            O + O3 --> 6.95266e-31 O2                                                               ', &
     ' 6.95266e-31 O + M --> M + O2                                                                       ', &
     '        O + M + O2 --> O3 + M                                                                       ', &
     '            H2 + O --> OH + HO2                                                                     ', &
     '          H2O2 + O --> OH + HO2                                                                     ', &
     '           O + HO2 --> OH + O2                                                                      ', &
     '          O3 + HO2 --> OH + 6.95266e-31 O2                                                          ', &
     '           H2 + OH --> HO2 + H2O                                                                    ', &
     '         H2O2 + OH --> HO2 + H2O                                                                    ', &
     '          OH + HO2 --> H2O + O2                                                                     ', &
     '            O + OH --> HO2 + O2                                                                     ', &
     '           O3 + OH --> HO2 + O2                                                                     ', &
     '    6.95266e-31 OH --> O + H2O                                                                      ', &
     '    6.95266e-31 OH --> H2O2                                                                         ', &
     '   6.95266e-31 HO2 --> H2O2 + O2                                                                    ', &
     '       HO2NO2 + OH --> NO2 + H2O + O2                                                               ', &
     '           O + NO2 --> NO + O2                                                                      ', &
     '          O3 + NO2 --> NO3 + O2                                                                     ', &
     '           O + NO2 --> NO3                                                                          ', &
     '         NO3 + HO2 --> NO2 + OH + O2                                                                ', &
     '          NO3 + NO --> 6.95266e-31 NO2                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '           O + NO3 --> NO2 + O2                                                                     ', &
     '          NO3 + OH --> NO2 + HO2                                                                    ', &
     '          HO2 + NO --> NO2 + OH                                                                     ', &
     '           O3 + NO --> NO2 + O2                                                                     ', &
     '            O + NO --> NO2                                                                          ', &
     '         N2O + O1D --> 6.95266e-31 NO                                                               ', &
     '         N2O + O1D --> O2 + N2                                                                      ', &
     '         NO2 + HO2 --> HO2NO2                                                                       ', &
     '         NO3 + NO2 --> N2O5                                                                         ', &
     '          NO2 + OH --> HNO3                                                                         ', &
     '         HNO3 + OH --> NO3 + H2O                                                                    ', &
     '        HO2NO2 + M --> NO2 + HO2 + M                                                                ', &
     '          N2O5 + M --> NO3 + NO2 + M                                                                ', &
     '        CH2O + HO2 --> HOCH2OO                                                                      ', &
     '        CH2O + NO3 --> CO + HNO3 + HO2                                                              ', &
     '          O + CH2O --> CO + OH + HO2                                                                ', &
     '         CH2O + OH --> CO + HO2 + H2O                                                               ', &
     ' 6.95266e-31 CH3O2 --> 6.95266e-31 CH2O + 6.95266e-31 HO2                                           ', &
     ' 6.95266e-31 CH3O2 --> CH3OH + CH2O                                                                 ', &
     '       CH3O2 + HO2 --> CH3OOH + O2                                                                  ', &
     '        CH3O2 + NO --> CH2O + NO2 + HO2                                                             ', &
     '        CH3OH + OH --> CH2O + HO2                                                                   ', &
     '       CH3OOH + OH --> 6.95266e-31 CH2O + 6.95266e-31 OH + 6.95266e-31 CH3O2 + H2O                  ', &
     '          CH4 + OH --> CH3O2 + H2O                                                                  ', &
     '          HCN + OH --> HO2                                                                          ', &
     '        HCOOH + OH --> HO2 + H2O + CO2                                                              ', &
     '     HOCH2OO + HO2 --> HCOOH                                                                        ', &
     '           HOCH2OO --> CH2O + HO2                                                                   ', &
     '      HOCH2OO + NO --> HCOOH + NO2 + HO2                                                            ', &
     '         HCN + O1D --> OH                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '           CO + OH --> HO2 + CO2                                                                    ', &
     '         C2H2 + OH --> 6.95266e-31 HCOOH + 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 OH + 6', &
     '         C2H4 + O3 --> 6.95266e-31 HCOOH + 6.95266e-31 CO + CH2O + 6.95266e-31 OH + 6.95266e-31 HO2 ', &
     '6.95266e-31 C2H5O2 --> 6.95266e-31 C2H5OH + 6.95266e-31 CH3CHO + 6.95266e-31 HO2                    ', &
     '    C2H5O2 + CH3O2 --> 6.95266e-31 C2H5OH + 6.95266e-31 CH3OH + 6.95266e-31 CH3CHO + 6.95266e-31 CH2', &
     '      C2H5O2 + HO2 --> C2H5OOH + O2                                                                 ', &
     '       C2H5O2 + NO --> CH3CHO + NO2 + HO2                                                           ', &
     '       C2H5OH + OH --> CH3CHO + HO2                                                                 ', &
     '      C2H5OOH + OH --> 6.95266e-31 C2H5O2 + 6.95266e-31 CH3CHO + 6.95266e-31 OH                     ', &
     '         C2H6 + OH --> C2H5O2 + H2O                                                                 ', &
     '      CH3CHO + NO3 --> HNO3 + CH3CO3                                                                ', &
     '       CH3CHO + OH --> CH3CO3 + H2O                                                                 ', &
     '        CH3CN + OH --> HO2                                                                          ', &
     '6.95266e-31 CH3CO3 --> 6.95266e-31 CH3O2 + 6.95266e-31 CO2                                          ', &
     '    CH3CO3 + CH3O2 --> 6.95266e-31 CH3COOH + CH2O + 6.95266e-31 CH3O2 + 6.95266e-31 HO2 + 6.95266e-3', &
     '      CH3CO3 + HO2 --> 6.95266e-31 CH3COOH + 6.95266e-31 CH3COOOH + 6.95266e-31 O3 + 6.95266e-31 OH ', &
     '       CH3CO3 + NO --> NO2 + CH3O2 + CO2                                                            ', &
     '      CH3COOH + OH --> CH3O2 + H2O + CO2                                                            ', &
     '     CH3COOOH + OH --> 6.95266e-31 CH2O + 6.95266e-31 CH3CO3 + H2O + 6.95266e-31 CO2                ', &
     '         EO2 + HO2 --> EOOH                                                                         ', &
     '          EO2 + NO --> 6.95266e-31 EO + 6.95266e-31 CH2O + NO2 + 6.95266e-31 HO2                    ', &
     '                EO --> 6.95266e-31 CH2O + HO2                                                       ', &
     '           EO + O2 --> GLYALD + HO2                                                                 ', &
     '       GLYALD + OH --> 6.95266e-31 GLYOXAL + 6.95266e-31 CH2O + HO2 + 6.95266e-31 CO2               ', &
     '      GLYOXAL + OH --> CO + HO2 + CO2                                                               ', &
     '          PAN + OH --> CH2O + NO3                                                                   ', &
     '         C2H4 + OH --> EO2                                                                          ', &
     '      CH3CO3 + NO2 --> PAN                                                                          ', &
     '           PAN + M --> CH3CO3 + NO2 + M                                                             ', &
     '        C3H6 + NO3 --> NOA                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '         C3H6 + O3 --> 6.95266e-31 CH3COOH + 6.95266e-31 CH4 + 6.95266e-31 HCOOH + 6.95266e-31 CO + ', &
     '    C3H7O2 + CH3O2 --> 6.95266e-31 CH3COCH3 + CH2O + HO2                                            ', &
     '      C3H7O2 + HO2 --> C3H7OOH + O2                                                                 ', &
     '       C3H7O2 + NO --> 6.95266e-31 CH3COCH3 + 6.95266e-31 CH3CHO + NO2 + HO2                        ', &
     '      C3H7OOH + OH --> C3H7O2 + H2O                                                                 ', &
     '         C3H8 + OH --> C3H7O2 + H2O                                                                 ', &
     '    CH3COCHO + NO3 --> CO + HNO3 + CH3CO3                                                           ', &
     '     CH3COCHO + OH --> CO + CH3CO3 + H2O                                                            ', &
     '         HYAC + OH --> CH3COCHO + HO2                                                               ', &
     '          NOA + OH --> CH3COCHO + NO2                                                               ', &
     '         PO2 + HO2 --> POOH + O2                                                                    ', &
     '          PO2 + NO --> CH3CHO + CH2O + NO2 + HO2                                                    ', &
     '         POOH + OH --> 6.95266e-31 PO2 + 6.95266e-31 HYAC + 6.95266e-31 OH + H2O                    ', &
     '       RO2 + CH3O2 --> 6.95266e-31 CH3OH + 6.95266e-31 HYAC + 6.95266e-31 CH3COCHO + 6.95266e-31 CH2', &
     '         RO2 + HO2 --> 6.95266e-31 ROOH + 6.95266e-31 CH2O + 6.95266e-31 CH3CO3 + 6.95266e-31 OH    ', &
     '          RO2 + NO --> CH2O + CH3CO3 + NO2                                                          ', &
     '         ROOH + OH --> RO2 + H2O                                                                    ', &
     '         C3H6 + OH --> PO2                                                                          ', &
     '     CH3COCH3 + OH --> RO2 + H2O                                                                    ', &
     '      BIGENE + NO3 --> 6.95266e-31 CH3COCH3 + CH3CHO + 6.95266e-31 CH2O + NO2                       ', &
     '       BIGENE + OH --> ENEO2                                                                        ', &
     '        ENEO2 + NO --> 6.95266e-31 CH3COCH3 + CH3CHO + 6.95266e-31 CH2O + NO2 + HO2                 ', &
     '        ENEO2 + NO --> HONITR                                                                       ', &
     '       HONITR + OH --> ONITR + HO2                                                                  ', &
     '   MACRO2 + CH3CO3 --> 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 HYAC + 6.95266e-31 CH3COCHO', &
     '    MACRO2 + CH3O2 --> 6.95266e-31 CH3OH + 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 HYAC + ', &
     '      MACRO2 + HO2 --> MACROOH                                                                      ', &
     '      MACRO2 + NO3 --> 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 HYAC + 6.95266e-31 CH3COCHO', &
     '       MACRO2 + NO --> 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 HYAC + 6.95266e-31 CH3COCHO', &
     '       MACRO2 + NO --> HONITR                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '         MACR + O3 --> 6.95266e-31 HCOOH + 6.95266e-31 CO + 6.95266e-31 CH3COCHO + 6.95266e-31 CH2O ', &
     '         MACR + OH --> 6.95266e-31 MACRO2 + 6.95266e-31 MCO3 + 6.95266e-31 H2O                      ', &
     '      MACROOH + OH --> 6.95266e-31 MACRO2 + 6.95266e-31 OH + 6.95266e-31 MCO3 + 6.95266e-31 HO2     ', &
     '     CH3CO3 + MCO3 --> CH2O + CH3CO3 + CH3O2 + 6.95266e-31 CO2                                      ', &
     '      MCO3 + CH3O2 --> 6.95266e-31 CH2O + CH3CO3 + HO2 + CO2                                        ', &
     '        MCO3 + HO2 --> 6.95266e-31 CH3COOH + 6.95266e-31 CH3COOOH + 6.95266e-31 CH2O + 6.95266e-31 O', &
     '  6.95266e-31 MCO3 --> 6.95266e-31 CH2O + 6.95266e-31 CH3CO3 + 6.95266e-31 CO2                      ', &
     '         MCO3 + NO --> CH2O + CH3CO3 + NO2                                                          ', &
     '        NO3 + MCO3 --> CH2O + CH3CO3 + NO2                                                          ', &
     '       MEKO2 + HO2 --> 6.95266e-31 MEKOOH + 6.95266e-31 CH3CHO + 6.95266e-31 CH3CO3 + 6.95266e-31 OH', &
     '        MEKO2 + NO --> CH3CHO + CH3CO3 + NO2                                                        ', &
     '          MEK + OH --> MEKO2                                                                        ', &
     '       MEKOOH + OH --> MEKO2                                                                        ', &
     '         MPAN + OH --> 6.95266e-31 HYAC + 6.95266e-31 CH2O + 6.95266e-31 NO3 + 6.95266e-31 HO2 + 6.9', &
     '          MVK + O3 --> 6.95266e-31 HCOOH + 6.95266e-31 CO + 6.95266e-31 CH3CHO + 6.95266e-31 CH3COCH', &
     '          MVK + OH --> MACRO2                                                                       ', &
     '    NO2 + MCO3 + M --> MPAN + M                                                                     ', &
     '          MPAN + M --> NO2 + MCO3 + M                                                               ', &
     '       ALKNIT + OH --> 6.95266e-31 CH3COCH3 + 6.95266e-31 CH3CHO + 6.95266e-31 CH2O + NO2           ', &
     '       ALKO2 + HO2 --> ALKOOH                                                                       ', &
     '        ALKO2 + NO --> 6.95266e-31 MEK + 6.95266e-31 CH3COCH3 + 6.95266e-31 CH3CHO + 6.95266e-31 CH2', &
     '        ALKO2 + NO --> ALKNIT                                                                       ', &
     '       ALKOOH + OH --> ALKO2                                                                        ', &
     '       BIGALK + OH --> ALKO2                                                                        ', &
     '        HPALD + OH --> XO2                                                                          ', &
     '      HYDRALD + OH --> XO2                                                                          ', &
     '        IEPOX + OH --> XO2                                                                          ', &
     '  ISOPAO2 + CH3CO3 --> 6.95266e-31 MACR + CH2O + 6.95266e-31 MVK + CH3O2 + HO2 + CO2                ', &
     '   ISOPAO2 + CH3O2 --> 6.95266e-31 CH3OH + 6.95266e-31 MACR + 6.95266e-31 CH2O + 6.95266e-31 MVK + H', &
     '     ISOPAO2 + HO2 --> ISOPOOH                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '      ISOPAO2 + NO --> 6.95266e-31 ISOPNITA + 6.95266e-31 MACR + 6.95266e-31 CH2O + 6.95266e-31 MVK ', &
     '     ISOPAO2 + NO3 --> 6.95266e-31 MACR + CH2O + 6.95266e-31 MVK + NO2 + HO2                        ', &
     '  ISOPBO2 + CH3CO3 --> HYDRALD + CH3O2 + HO2                                                        ', &
     '   ISOPBO2 + CH3O2 --> 6.95266e-31 HYDRALD + 6.95266e-31 CH3OH + 6.95266e-31 CH2O + HO2             ', &
     '     ISOPBO2 + HO2 --> ISOPOOH                                                                      ', &
     '           ISOPBO2 --> HPALD + HO2                                                                  ', &
     '      ISOPBO2 + NO --> 6.95266e-31 HYDRALD + 6.95266e-31 ISOPNITB + 6.95266e-31 GLYOXAL + 6.95266e-3', &
     '     ISOPBO2 + NO3 --> 6.95266e-31 HYDRALD + 6.95266e-31 GLYOXAL + 6.95266e-31 GLYALD + 6.95266e-31 ', &
     '     ISOPNITA + OH --> 6.95266e-31 GLYALD + 6.95266e-31 HYAC + 6.95266e-31 HONITR + 6.95266e-31 CH2O', &
     '     ISOPNITB + OH --> 6.95266e-31 NOA + 6.95266e-31 GLYALD + 6.95266e-31 HYAC + 6.95266e-31 HONITR ', &
     '        ISOP + NO3 --> ISOPNO3                                                                      ', &
     '  ISOPNO3 + CH3CO3 --> NC4CHO + CH3O2 + HO2                                                         ', &
     '   ISOPNO3 + CH3O2 --> 6.95266e-31 NC4CH2OH + 6.95266e-31 CH3OH + 6.95266e-31 NC4CHO + 6.95266e-31 C', &
     '     ISOPNO3 + HO2 --> ISOPNOOH                                                                     ', &
     '      ISOPNO3 + NO --> NC4CHO + NO2 + HO2                                                           ', &
     '     ISOPNO3 + NO3 --> NC4CHO + NO2 + HO2                                                           ', &
     '     ISOPNOOH + OH --> NOA + HO2                                                                    ', &
     '         ISOP + O3 --> 6.95266e-31 HCOOH + 6.95266e-31 CO + 6.95266e-31 C3H6 + 6.95266e-31 MACR + 6.', &
     '         ISOP + OH --> 6.95266e-31 ISOPAO2 + 6.95266e-31 ISOPBO2                                    ', &
     '      ISOPOOH + OH --> 6.95266e-31 IEPOX + 6.95266e-31 XO2 + 6.95266e-31 OH                         ', &
     '     NC4CH2OH + OH --> NOA + GLYALD + HO2                                                           ', &
     '       NC4CHO + OH --> NOA + GLYOXAL + HO2                                                          ', &
     '      XO2 + CH3CO3 --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 HYAC ', &
     '       XO2 + CH3O2 --> 6.95266e-31 CH3OH + 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 GLYALD', &
     '         XO2 + HO2 --> XOOH                                                                         ', &
     '          XO2 + NO --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 HYAC ', &
     '         XO2 + NO3 --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 GLYALD + 6.95266e-31 HYAC ', &
     '         XOOH + OH --> 6.95266e-31 XO2 + 6.95266e-31 OH                                             ', &
     '    HMPROPO2 + HO2 --> 6.95266e-31 CH3COCH3 + 6.95266e-31 OH + 6.95266e-31 HO2 + 6.95266e-31 CO2    ', &
     '     HMPROPO2 + NO --> CH3COCH3 + NO2 + HO2 + CO2                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '       HMPROP + OH --> HMPROPO2                                                                     ', &
     '         MBO + NO3 --> MBONO3O2                                                                     ', &
     '    MBONO3O2 + HO2 --> M                                                                            ', &
     '     MBONO3O2 + NO --> 6.95266e-31 HMPROP + 6.95266e-31 CH3COCH3 + 6.95266e-31 HONITR + 6.95266e-31 ', &
     '    MBONO3O2 + NO3 --> 6.95266e-31 HMPROP + 6.95266e-31 CH3COCH3 + 6.95266e-31 HONITR + 6.95266e-31 ', &
     '     MBOO2 + CH3O2 --> 6.95266e-31 CH3OH + 6.95266e-31 HMPROP + 6.95266e-31 CH3COCH3 + 6.95266e-31 G', &
     '       MBOO2 + HO2 --> MBOOOH                                                                       ', &
     '        MBOO2 + NO --> 6.95266e-31 HMPROP + 6.95266e-31 CH3COCH3 + 6.95266e-31 GLYALD + 6.95266e-31 ', &
     '          MBO + O3 --> 6.95266e-31 HCOOH + 6.95266e-31 HMPROP + 6.95266e-31 CH3COCH3 + 6.95266e-31 C', &
     '          MBO + OH --> MBOO2                                                                        ', &
     '       MBOOOH + OH --> 6.95266e-31 MBOO2 + 6.95266e-31 OH                                           ', &
     '      ACBZO2 + HO2 --> 6.95266e-31 C6H5O2 + 6.95266e-31 OH                                          ', &
     '       ACBZO2 + NO --> C6H5O2 + NO2                                                                 ', &
     '      BENZENE + OH --> 6.95266e-31 BEPOMUC + 6.95266e-31 PHENOL + 6.95266e-31 BENZO2 + 6.95266e-31 H', &
     '      BENZO2 + HO2 --> BENZOOH                                                                      ', &
     '       BENZO2 + NO --> 6.95266e-31 BIGALD1 + GLYOXAL + NO2 + HO2                                    ', &
     '      BENZOOH + OH --> BENZO2                                                                       ', &
     '        BZALD + OH --> ACBZO2                                                                       ', &
     '        BZOO + HO2 --> BZOOH                                                                        ', &
     '        BZOOH + OH --> BZOO                                                                         ', &
     '         BZOO + NO --> BZALD + NO2 + HO2                                                            ', &
     '      C6H5O2 + HO2 --> C6H5OOH                                                                      ', &
     '       C6H5O2 + NO --> PHENO + NO2                                                                  ', &
     '      C6H5OOH + OH --> C6H5O2                                                                       ', &
     '       CRESOL + OH --> 6.95266e-31 PHENO2 + 6.95266e-31 PHENO + 6.95266e-31 HO2                     ', &
     '    DICARBO2 + HO2 --> 6.95266e-31 CO + 6.95266e-31 CH3COCHO + 6.95266e-31 OH + 6.95266e-31 CH3O2 + ', &
     '     DICARBO2 + NO --> 6.95266e-31 CO + 6.95266e-31 CH3COCHO + NO2 + 6.95266e-31 CH3O2 + 6.95266e-31', &
     '    DICARBO2 + NO2 --> M                                                                            ', &
     '       MALO2 + HO2 --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 HO2                       ', &
     '        MALO2 + NO --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + NO2 + 6.95266e-31 HO2                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '       MALO2 + NO2 --> M                                                                            ', &
     '     MDIALO2 + HO2 --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 CH3COCHO + 6.95266e-31 OH ', &
     '      MDIALO2 + NO --> 6.95266e-31 GLYOXAL + 6.95266e-31 CO + 6.95266e-31 CH3COCHO + NO2 + 6.95266e-', &
     '     MDIALO2 + NO2 --> M                                                                            ', &
     '      PHENO2 + HO2 --> PHENOOH                                                                      ', &
     '       PHENO2 + NO --> 6.95266e-31 GLYOXAL + NO2 + HO2                                              ', &
     '       PHENOL + OH --> 6.95266e-31 PHENO2 + 6.95266e-31 PHENO + 6.95266e-31 HO2                     ', &
     '       PHENO + NO2 --> M                                                                            ', &
     '        PHENO + O3 --> C6H5O2                                                                       ', &
     '      PHENOOH + OH --> PHENO2                                                                       ', &
     '      ACBZO2 + NO2 --> PBZNIT                                                                       ', &
     '       TOLO2 + HO2 --> TOLOOH                                                                       ', &
     '        TOLO2 + NO --> 6.95266e-31 BIGALD2 + 6.95266e-31 BIGALD1 + 6.95266e-31 BIGALD3 + 6.95266e-31', &
     '       TOLOOH + OH --> TOLO2                                                                        ', &
     '      TOLUENE + OH --> 6.95266e-31 CRESOL + 6.95266e-31 TEPOMUC + 6.95266e-31 BZOO + 6.95266e-31 TOL', &
     '        PBZNIT + M --> ACBZO2 + NO2 + M                                                             ', &
     '      XYLENES + OH --> 6.95266e-31 TEPOMUC + 6.95266e-31 XYLOL + 6.95266e-31 BZOO + 6.95266e-31 XYLE', &
     '     XYLENO2 + HO2 --> XYLENOOH                                                                     ', &
     '      XYLENO2 + NO --> 6.95266e-31 BIGALD2 + 6.95266e-31 BIGALD4 + 6.95266e-31 BIGALD1 + 6.95266e-31', &
     '     XYLENOOH + OH --> XYLENO2                                                                      ', &
     '     XYLOLO2 + HO2 --> XYLOLOOH                                                                     ', &
     '      XYLOLO2 + NO --> 6.95266e-31 GLYOXAL + 6.95266e-31 CH3COCHO + NO2 + HO2                       ', &
     '        XYLOL + OH --> 6.95266e-31 PHENO + 6.95266e-31 XYLOLO2 + 6.95266e-31 HO2                    ', &
     '     XYLOLOOH + OH --> XYLOLO2                                                                      ', &
     '        APIN + NO3 --> NTERPO2                                                                      ', &
     '         APIN + O3 --> 6.95266e-31 BIGALK + 6.95266e-31 HCOOH + 6.95266e-31 BIGALD + 6.95266e-31 CH3', &
     '         APIN + OH --> TERPO2                                                                       ', &
     '       BCARY + NO3 --> NTERPO2                                                                      ', &
     '        BCARY + O3 --> 6.95266e-31 BIGALK + 6.95266e-31 HCOOH + 6.95266e-31 BIGALD + 6.95266e-31 CH3', &
     '        BCARY + OH --> TERPO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '        BPIN + NO3 --> NTERPO2                                                                      ', &
     '         BPIN + O3 --> 6.95266e-31 BIGALK + 6.95266e-31 HCOOH + 6.95266e-31 BIGALD + 6.95266e-31 CH3', &
     '         BPIN + OH --> TERPO2                                                                       ', &
     '       LIMON + NO3 --> NTERPO2                                                                      ', &
     '        LIMON + O3 --> 6.95266e-31 BIGALK + 6.95266e-31 HCOOH + 6.95266e-31 BIGALD + 6.95266e-31 CH3', &
     '        LIMON + OH --> TERPO2                                                                       ', &
     '        MYRC + NO3 --> NTERPO2                                                                      ', &
     '         MYRC + O3 --> 6.95266e-31 BIGALK + 6.95266e-31 HCOOH + 6.95266e-31 BIGALD + 6.95266e-31 CH3', &
     '         MYRC + OH --> TERPO2                                                                       ', &
     '   NTERPO2 + CH3O2 --> 6.95266e-31 TERPNIT + 6.95266e-31 CH3OH + 6.95266e-31 TERPROD1 + 6.95266e-31 ', &
     '     NTERPO2 + HO2 --> NTERPOOH                                                                     ', &
     '      NTERPO2 + NO --> 6.95266e-31 TERPNIT + 6.95266e-31 TERPROD1 + 6.95266e-31 NO2                 ', &
     '     NTERPO2 + NO3 --> TERPROD1 + 6.95266e-31 NO2                                                   ', &
     '     NTERPOOH + OH --> NTERPO2                                                                      ', &
     '   TERP2O2 + CH3O2 --> 6.95266e-31 CH3OH + 6.95266e-31 CH3COCH3 + 6.95266e-31 CO + 6.95266e-31 GLYAL', &
     '     TERP2O2 + HO2 --> TERP2OOH                                                                     ', &
     '      TERP2O2 + NO --> 6.95266e-31 ONITR + 6.95266e-31 CH3COCH3 + 6.95266e-31 CO + 6.95266e-31 GLYAL', &
     '     TERP2OOH + OH --> TERP2O2                                                                      ', &
     '      TERPNIT + OH --> TERPROD1 + NO2                                                               ', &
     '    TERPO2 + CH3O2 --> 6.95266e-31 CH3OH + 6.95266e-31 CH3COCH3 + TERPROD1 + 6.95266e-31 CH2O + HO2 ', &
     '      TERPO2 + HO2 --> TERPOOH                                                                      ', &
     '       TERPO2 + NO --> 6.95266e-31 TERPNIT + 6.95266e-31 CH3COCH3 + 6.95266e-31 TERPROD1 + 6.95266e-', &
     '      TERPOOH + OH --> TERPO2                                                                       ', &
     '    TERPROD1 + NO3 --> 6.95266e-31 TERP2O2 + 6.95266e-31 NTERPO2                                    ', &
     '     TERPROD1 + OH --> TERP2O2                                                                      ', &
     '     TERPROD2 + OH --> 6.95266e-31 CH3COCH3 + 6.95266e-31 CO + 6.95266e-31 RO2 + 6.95266e-31 CH2O + ', &
     '         DMS + NO3 --> SO2 + HNO3                                                                   ', &
     '          DMS + OH --> SO2                                                                          ', &
     '          NH3 + OH --> H2O                                                                          ', &
     '          DMS + OH --> 6.95266e-31 SO2 + 6.95266e-31 HO2                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(14) :: EQN_NAMES_11 = (/ &
     '               HO2 --> 6.95266e-31 H2O2                                                             ', &
     '              N2O5 --> 6.95266e-31 HNO3                                                             ', &
     '               NO2 --> 6.95266e-31 HNO3 + 6.95266e-31 OH + 6.95266e-31 NO                           ', &
     '               NO3 --> HNO3                                                                         ', &
     '            HONITR --> HNO3                                                                         ', &
     '          ISOPNITA --> HNO3                                                                         ', &
     '          ISOPNITB --> HNO3                                                                         ', &
     '          NC4CH2OH --> HNO3                                                                         ', &
     '            NC4CHO --> HNO3                                                                         ', &
     '          NTERPOOH --> HNO3                                                                         ', &
     '             ONITR --> HNO3                                                                         ', &
     '           TERPNIT --> HNO3                                                                         ', &
     '           GLYOXAL --> CO2                                                                          ', &
     '          SO2 + OH --> SO4                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(344) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11 /)

! INLINED global variables

! End INLINED global variables


END MODULE t1_mozcart_Monitor
