! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc99_mosaic_4bin_vbs2_Monitor.f90
! Time                 : Mon Sep 26 23:37:49 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/saprc99_mosaic_4bin_vbs2
! Equation file        : saprc99_mosaic_4bin_vbs2.kpp
! Output root filename : saprc99_mosaic_4bin_vbs2
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc99_mosaic_4bin_vbs2_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'H2SO4       ','CO2         ','PCG1_B_C    ', &
     'PCG1_B_O    ','PCG1_F_C    ','PCG1_F_O    ', &
     'HCOOH       ','CCO_OH      ','RCO_OH      ', &
     'CCO_OOH     ','RCO_OOH     ','XN          ', &
     'XC          ','NUME        ','DEN         ', &
     'ANT1_c      ','ANT1_o      ','BIOG1_c     ', &
     'BIOG1_o     ','PSD1        ','PSD2        ', &
     'OPCG1_B_O   ','PCG2_B_O    ','OPCG1_F_O   ', &
     'PCG2_F_O    ','O1D         ','PCG2_B_C    ', &
     'OPCG1_B_C   ','PCG2_F_C    ','OPCG1_F_C   ', &
     'CH4         ','SO2         ','C2H6        ', &
     'PAN         ','PAN2        ','PBZN        ', &
     'MA_PAN      ','H2O2        ','C3H8        ', &
     'BACL        ','ETOH        ','N2O5        ', &
     'HONO        ','ALK3        ','TBU_O       ', &
     'ALK5        ','COOH        ','HOCOO       ', &
     'BZNO2_O     ','ARO2        ','HNO4        ', &
     'MEOH        ','ALK4        ','ARO1        ', &
     'DCB2        ','DCB3        ','CRES        ', &
     'DCB1        ','C2H2        ','ROOH        ', &
     'NPHE        ','BALD        ','PHEN        ', &
     'MGLY        ','CO          ','HNO3        ', &
     'ETHENE      ','ACET        ','C3H6        ', &
     'BZ_O        ','ISOPRENE    ','OLE1        ', &
     'R2O2        ','METHACRO    ','SESQ        ', &
     'TERP        ','GLY         ','ISOPROD     ', &
     'CCHO        ','OLE2        ','MVK         ', &
     'HCHO        ','RNO3        ','O3P         ', &
     'RCHO        ','MEK         ','PROD2       ', &
     'O3          ','CCO_O2      ','RO2_R       ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(12) :: SPC_NAMES_1 = (/ &
     'RO2_N       ','NO2         ','NO3         ', &
     'C_O2        ','BZCO_O2     ','MA_RCO3     ', &
     'HO2         ','OH          ','RCO_O2      ', &
     'NO          ','H2O         ','M           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(102) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '                  NO2 --> O3P + NO                                                                  ', &
     '              O3P + M --> O3                                                                        ', &
     '             O3P + O3 --> M                                                                         ', &
     '         O3P + NO + M --> NO2                                                                       ', &
     '            O3P + NO2 --> NO                                                                        ', &
     '            O3P + NO2 --> NO3                                                                       ', &
     '              O3 + NO --> NO2                                                                       ', &
     '             O3 + NO2 --> NO3                                                                       ', &
     '             NO3 + NO --> 6.95329e-31 NO2                                                           ', &
     '   6.95329e-31 NO + M --> 6.95329e-31 NO2                                                           ', &
     '            NO2 + NO3 --> N2O5                                                                      ', &
     '                 N2O5 --> NO2 + NO3                                                                 ', &
     '           N2O5 + H2O --> 6.95329e-31 HNO3                                                          ', &
     '            NO2 + NO3 --> NO2 + NO                                                                  ', &
     '                  NO3 --> NO                                                                        ', &
     '                  NO3 --> O3P + NO2                                                                 ', &
     '                   O3 --> O3P                                                                       ', &
     '                   O3 --> O1D                                                                       ', &
     '            O1D + H2O --> 6.95329e-31 OH                                                            ', &
     '              O1D + M --> O3P                                                                       ', &
     '              OH + NO --> PSD1 + HONO                                                               ', &
     '                 HONO --> OH + NO                                                                   ', &
     '                 HONO --> NO2 + HO2                                                                 ', &
     '            HONO + OH --> PSD1 + NO2                                                                ', &
     '             NO2 + OH --> PSD1 + HNO3                                                               ', &
     '             NO3 + OH --> PSD1 + NO2 + HO2                                                          ', &
     '            HNO3 + OH --> PSD1 + NO3                                                                ', &
     '                 HNO3 --> NO2 + OH                                                                  ', &
     '              CO + OH --> PSD1 + HO2                                                                ', &
     '              O3 + OH --> PSD1 + HO2                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '             HO2 + NO --> NO2 + OH                                                                  ', &
     '            NO2 + HO2 --> HNO4                                                                      ', &
     '                 HNO4 --> NO2 + HO2                                                                 ', &
     '                 HNO4 --> 6.95329e-31 NO2 + 6.95329e-31 NO3 + 6.95329e-31 HO2 + 6.95329e-31 OH      ', &
     '            HNO4 + OH --> NO2                                                                       ', &
     '             O3 + HO2 --> OH                                                                        ', &
     '      6.95329e-31 HO2 --> H2O2                                                                      ', &
     '6.95329e-31 HO2 + H2O --> H2O2                                                                      ', &
     '            NO3 + HO2 --> 6.95329e-31 HNO3 + 6.95329e-31 NO2 + 6.95329e-31 OH                       ', &
     '      6.95329e-31 NO3 --> 6.95329e-31 NO2                                                           ', &
     '                 H2O2 --> 6.95329e-31 OH                                                            ', &
     '            H2O2 + OH --> HO2                                                                       ', &
     '             HO2 + OH --> PSD1 + H2O + M                                                            ', &
     '             SO2 + OH --> H2SO4 + PSD1 + HO2                                                        ', &
     '               OH + M --> PSD1 + HO2                                                                ', &
     '            C_O2 + NO --> NUME + HCHO + NO2 + HO2                                                   ', &
     '           C_O2 + HO2 --> DEN + COOH                                                                ', &
     '           NO3 + C_O2 --> NUME + HCHO + NO2 + HO2                                                   ', &
     '     6.95329e-31 C_O2 --> DEN + MEOH + HCHO                                                         ', &
     '     6.95329e-31 C_O2 --> DEN + 6.95329e-31 HCHO + 6.95329e-31 HO2                                  ', &
     '           RO2_R + NO --> NUME + NO2 + HO2                                                          ', &
     '          RO2_R + HO2 --> DEN + ROOH                                                                ', &
     '          RO2_R + NO3 --> NUME + NO2 + HO2                                                          ', &
     '         RO2_R + C_O2 --> DEN + 6.95329e-31 MEOH + 6.95329e-31 HCHO + HO2                           ', &
     '    6.95329e-31 RO2_R --> DEN + HO2                                                                 ', &
     '            R2O2 + NO --> NUME + NO2                                                                ', &
     '           R2O2 + HO2 --> DEN + HO2                                                                 ', &
     '           R2O2 + NO3 --> NUME + NO2                                                                ', &
     '          R2O2 + C_O2 --> DEN + C_O2                                                                ', &
     '         R2O2 + RO2_R --> DEN + RO2_R                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '     6.95329e-31 R2O2 --> DEN + 6.95329e-31 R2O2                                                    ', &
     '           RO2_N + NO --> NUME + RNO3                                                               ', &
     '          RO2_N + HO2 --> DEN + ROOH                                                                ', &
     '         RO2_N + C_O2 --> DEN + 6.95329e-31 MEOH + 6.95329e-31 HCHO + 6.95329e-31 MEK + 6.95329e-31 ', &
     '          RO2_N + NO3 --> NUME + MEK + NO2 + HO2                                                    ', &
     '        RO2_R + RO2_N --> DEN + 6.95329e-31 MEK + 6.95329e-31 PROD2 + HO2                           ', &
     '         R2O2 + RO2_N --> DEN + RO2_N                                                               ', &
     '    6.95329e-31 RO2_N --> DEN + MEK + PROD2 + HO2                                                   ', &
     '         CCO_O2 + NO2 --> PAN                                                                       ', &
     '                  PAN --> CCO_O2 + NO2                                                              ', &
     '          CCO_O2 + NO --> NO2 + C_O2                                                                ', &
     '         CCO_O2 + HO2 --> 6.95329e-31 CCO_OH + 6.95329e-31 CCO_OOH + 6.95329e-31 O3                 ', &
     '         CCO_O2 + NO3 --> NO2 + C_O2                                                                ', &
     '        CCO_O2 + C_O2 --> CCO_OH + HCHO                                                             ', &
     '       CCO_O2 + RO2_R --> CCO_OH                                                                    ', &
     '        R2O2 + CCO_O2 --> CCO_O2                                                                    ', &
     '       CCO_O2 + RO2_N --> CCO_OH + PROD2                                                            ', &
     '   6.95329e-31 CCO_O2 --> 6.95329e-31 C_O2                                                          ', &
     '         NO2 + RCO_O2 --> PAN2                                                                      ', &
     '                 PAN2 --> NO2 + RCO_O2                                                              ', &
     '          RCO_O2 + NO --> CCHO + RO2_R + NO2                                                        ', &
     '         HO2 + RCO_O2 --> 6.95329e-31 RCO_OH + 6.95329e-31 RCO_OOH + 6.95329e-31 O3                 ', &
     '         NO3 + RCO_O2 --> CCHO + RO2_R + NO2                                                        ', &
     '        C_O2 + RCO_O2 --> RCO_OH + HCHO                                                             ', &
     '       RO2_R + RCO_O2 --> RCO_OH                                                                    ', &
     '        R2O2 + RCO_O2 --> RCO_O2                                                                    ', &
     '       RO2_N + RCO_O2 --> RCO_OH + PROD2                                                            ', &
     '      CCO_O2 + RCO_O2 --> CCHO + RO2_R + C_O2                                                       ', &
     '   6.95329e-31 RCO_O2 --> 6.95329e-31 CCHO + 6.95329e-31 RO2_R                                      ', &
     '        NO2 + BZCO_O2 --> PBZN                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '                 PBZN --> NO2 + BZCO_O2                                                             ', &
     '         BZCO_O2 + NO --> BZ_O + R2O2 + NO2                                                         ', &
     '        BZCO_O2 + HO2 --> 6.95329e-31 RCO_OH + 6.95329e-31 RCO_OOH + 6.95329e-31 O3                 ', &
     '        NO3 + BZCO_O2 --> BZ_O + R2O2 + NO2                                                         ', &
     '       C_O2 + BZCO_O2 --> RCO_OH + HCHO                                                             ', &
     '      RO2_R + BZCO_O2 --> RCO_OH                                                                    ', &
     '       R2O2 + BZCO_O2 --> BZCO_O2                                                                   ', &
     '      RO2_N + BZCO_O2 --> RCO_OH + PROD2                                                            ', &
     '     CCO_O2 + BZCO_O2 --> BZ_O + R2O2 + C_O2                                                        ', &
     '     BZCO_O2 + RCO_O2 --> BZ_O + R2O2 + CCHO + RO2_R                                                ', &
     '  6.95329e-31 BZCO_O2 --> 6.95329e-31 BZ_O + 6.95329e-31 R2O2                                       ', &
     '        NO2 + MA_RCO3 --> MA_PAN                                                                    ', &
     '               MA_PAN --> NO2 + MA_RCO3                                                             ', &
     '         MA_RCO3 + NO --> HCHO + CCO_O2 + NO2                                                       ', &
     '        MA_RCO3 + HO2 --> 6.95329e-31 RCO_OH + 6.95329e-31 RCO_OOH + 6.95329e-31 O3                 ', &
     '        NO3 + MA_RCO3 --> HCHO + CCO_O2 + NO2                                                       ', &
     '       C_O2 + MA_RCO3 --> RCO_OH + HCHO                                                             ', &
     '      RO2_R + MA_RCO3 --> RCO_OH                                                                    ', &
     '       R2O2 + MA_RCO3 --> MA_RCO3                                                                   ', &
     '      RO2_N + MA_RCO3 --> 6.95329e-31 RCO_OH                                                        ', &
     '     CCO_O2 + MA_RCO3 --> HCHO + CCO_O2 + C_O2                                                      ', &
     '     MA_RCO3 + RCO_O2 --> CCHO + HCHO + CCO_O2 + RO2_R                                              ', &
     '    BZCO_O2 + MA_RCO3 --> BZ_O + R2O2 + HCHO + CCO_O2                                               ', &
     '  6.95329e-31 MA_RCO3 --> 6.95329e-31 HCHO + 6.95329e-31 CCO_O2                                     ', &
     '          TBU_O + NO2 --> RNO3                                                                      ', &
     '                TBU_O --> ACET + C_O2                                                               ', &
     '           BZ_O + NO2 --> NPHE                                                                      ', &
     '           BZ_O + HO2 --> PHEN                                                                      ', &
     '                 BZ_O --> PHEN                                                                      ', &
     '        BZNO2_O + NO2 --> 6.95329e-31 XN + 6.95329e-31 XC                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '        BZNO2_O + HO2 --> NPHE                                                                      ', &
     '              BZNO2_O --> NPHE                                                                      ', &
     '                 HCHO --> CO + 6.95329e-31 HO2                                                      ', &
     '                 HCHO --> CO                                                                        ', &
     '            HCHO + OH --> PSD1 + CO + HO2                                                           ', &
     '           HCHO + HO2 --> HOCOO                                                                     ', &
     '                HOCOO --> HCHO + HO2                                                                ', &
     '           HOCOO + NO --> HCOOH + NO2 + HO2                                                         ', &
     '           HCHO + NO3 --> CO + HNO3 + HO2                                                           ', &
     '            CCHO + OH --> PSD1 + CCO_O2                                                             ', &
     '                 CCHO --> CO + C_O2 + HO2                                                           ', &
     '           CCHO + NO3 --> HNO3 + CCO_O2                                                             ', &
     '            RCHO + OH --> PSD1 + 6.95329e-31 CO + 6.95329e-31 CCHO + 6.95329e-31 RO2_R + 6.95329e-31', &
     '                 RCHO --> CO + CCHO + RO2_R + HO2                                                   ', &
     '           RCHO + NO3 --> HNO3 + RCO_O2                                                             ', &
     '            ACET + OH --> PSD1 + R2O2 + HCHO + CCO_O2                                               ', &
     '                 ACET --> CCO_O2 + C_O2                                                             ', &
     '             MEK + OH --> PSD1 + 6.95329e-31 R2O2 + 6.95329e-31 CCHO + 6.95329e-31 HCHO + 6.95329e-3', &
     '                  MEK --> CCHO + CCO_O2 + RO2_R                                                     ', &
     '            MEOH + OH --> PSD1 + HCHO + HO2                                                         ', &
     '            ETOH + OH --> PSD1 + 6.95329e-31 CCHO + 6.95329e-31 HCHO + 6.95329e-31 RO2_R + 6.95329e-', &
     '            COOH + OH --> PSD1 + 6.95329e-31 HCHO + 6.95329e-31 C_O2 + 6.95329e-31 OH               ', &
     '                 COOH --> HCHO + HO2 + OH                                                           ', &
     '            ROOH + OH --> PSD1 + RCHO + 6.95329e-31 RO2_R + 6.95329e-31 OH                          ', &
     '                 ROOH --> RCHO + HO2 + OH                                                           ', &
     '                  GLY --> 6.95329e-31 CO + 6.95329e-31 HO2                                          ', &
     '                  GLY --> CO + HCHO                                                                 ', &
     '             GLY + OH --> PSD1 + 6.95329e-31 CO + 6.95329e-31 HO2 + 6.95329e-31 RCO_O2              ', &
     '            GLY + NO3 --> 6.95329e-31 CO + HNO3 + 6.95329e-31 HO2 + 6.95329e-31 RCO_O2              ', &
     '                 MGLY --> CO + CCO_O2 + HO2                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '            MGLY + OH --> PSD1 + CO + CCO_O2                                                        ', &
     '           MGLY + NO3 --> CO + HNO3 + CCO_O2                                                        ', &
     '                 BACL --> 6.95329e-31 CCO_O2                                                        ', &
     '            PHEN + OH --> PSD1 + 6.95329e-31 BZ_O + 6.95329e-31 GLY + 6.95329e-31 RO2_R             ', &
     '           PHEN + NO3 --> HNO3 + BZ_O                                                               ', &
     '            CRES + OH --> PSD1 + 6.95329e-31 MGLY + 6.95329e-31 BZ_O + 6.95329e-31 RO2_R            ', &
     '           CRES + NO3 --> HNO3 + BZ_O                                                               ', &
     '           NPHE + NO3 --> BZNO2_O + HNO3                                                            ', &
     '            BALD + OH --> PSD1 + BZCO_O2                                                            ', &
     '                 BALD --> 6.95329e-31 XC                                                            ', &
     '           BALD + NO3 --> HNO3 + BZCO_O2                                                            ', &
     '        METHACRO + OH --> PSD1 + 6.95329e-31 MGLY + 6.95329e-31 CO + 6.95329e-31 HCHO + 6.95329e-31 ', &
     '        METHACRO + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 MGLY + 6.95329e-31 CO + 6.95329e-31 HCHO +', &
     '       METHACRO + NO3 --> 6.95329e-31 CO + 6.95329e-31 HNO3 + 6.95329e-31 RO2_R + 6.95329e-31 MA_RCO', &
     '       METHACRO + O3P --> RCHO                                                                      ', &
     '             METHACRO --> 6.95329e-31 CO + 6.95329e-31 HCHO + 6.95329e-31 CCO_O2 + 6.95329e-31 RO2_R', &
     '             MVK + OH --> PSD1 + 6.95329e-31 MGLY + 6.95329e-31 R2O2 + 6.95329e-31 HCHO + 6.95329e-3', &
     '             MVK + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 MGLY + 6.95329e-31 CO + 6.95329e-31 HCHO +', &
     '            MVK + O3P --> 6.95329e-31 RCHO + 6.95329e-31 MEK                                        ', &
     '                  MVK --> 6.95329e-31 CO + 6.95329e-31 PROD2 + 6.95329e-31 C_O2 + 6.95329e-31 MA_RCO', &
     '         ISOPROD + OH --> PSD1 + 6.95329e-31 MGLY + 6.95329e-31 CO + 6.95329e-31 GLY + 6.95329e-31 C', &
     '         ISOPROD + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 RCO_OH + 6.95329e-31 MGLY + 6.95329e-31 CO', &
     '        ISOPROD + NO3 --> 6.95329e-31 MGLY + 6.95329e-31 CO + 6.95329e-31 HNO3 + 6.95329e-31 HCHO + ', &
     '              ISOPROD --> 6.95329e-31 CO + 6.95329e-31 CCHO + 6.95329e-31 HCHO + 6.95329e-31 MEK + 6', &
     '           PROD2 + OH --> PSD1 + 6.95329e-31 CCHO + 6.95329e-31 HCHO + 6.95329e-31 RCHO + 6.95329e-3', &
     '                PROD2 --> 6.95329e-31 R2O2 + 6.95329e-31 CCHO + 6.95329e-31 HCHO + 6.95329e-31 RCHO ', &
     '            RNO3 + OH --> PSD1 + 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-31 CCHO + 6.95329e-3', &
     '                 RNO3 --> 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-31 CCHO + 6.95329e-31 HCHO ', &
     '            DCB1 + OH --> PSD1 + CO + RCHO + RO2_R                                                  ', &
     '            DCB1 + O3 --> 6.95329e-31 CO + GLY + 6.95329e-31 HO2 + 6.95329e-31 OH                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '            DCB2 + OH --> PSD1 + R2O2 + RCHO + CCO_O2                                               ', &
     '                 DCB2 --> 6.95329e-31 MGLY + CO + R2O2 + 6.95329e-31 GLY + 6.95329e-31 CCO_O2 + RO2_', &
     '            DCB3 + OH --> PSD1 + R2O2 + RCHO + CCO_O2                                               ', &
     '                 DCB3 --> 6.95329e-31 MGLY + CO + R2O2 + 6.95329e-31 GLY + 6.95329e-31 CCO_O2 + RO2_', &
     '             CH4 + OH --> PSD1 + C_O2                                                               ', &
     '          ETHENE + OH --> PSD1 + 6.95329e-31 CCHO + 6.95329e-31 HCHO + RO2_R                        ', &
     '          ETHENE + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 CO + HCHO + 6.95329e-31 HO2 + 6.95329e-31 ', &
     '         ETHENE + NO3 --> RCHO + RO2_R                                                              ', &
     '         ETHENE + O3P --> 6.95329e-31 CO + 6.95329e-31 GLY + 6.95329e-31 CCHO + 6.95329e-31 HCHO + 6', &
     '        ISOPRENE + OH --> PSD1 + 6.95329e-31 R2O2 + 6.95329e-31 METHACRO + 6.95329e-31 ISOPROD + 6.9', &
     '        ISOPRENE + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 RCO_OH + 6.95329e-31 CO + 6.95329e-31 R2O2', &
     '       ISOPRENE + NO3 --> 6.95329e-31 R2O2 + 6.95329e-31 ISOPROD + 6.95329e-31 RO2_R + 6.95329e-31 R', &
     '       ISOPRENE + O3P --> 6.95329e-31 R2O2 + 6.95329e-31 HCHO + 6.95329e-31 PROD2 + 6.95329e-31 RO2_', &
     '            TERP + OH --> PSD1 + 6.95329e-31 R2O2 + 6.95329e-31 HCHO + 6.95329e-31 RCHO + 6.95329e-3', &
     '            TERP + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 RCO_OH + 6.95329e-31 BACL + 6.95329e-31 CO', &
     '           TERP + NO3 --> 6.95329e-31 R2O2 + 6.95329e-31 RNO3 + 6.95329e-31 RCHO + 6.95329e-31 RO2_R', &
     '           TERP + O3P --> 6.95329e-31 RCHO + 6.95329e-31 PROD2                                      ', &
     '            SESQ + OH --> PSD1 + 6.95329e-31 R2O2 + 6.95329e-31 HCHO + 6.95329e-31 RCHO + 6.95329e-3', &
     '            SESQ + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 RCO_OH + 6.95329e-31 BACL + 6.95329e-31 CO', &
     '           SESQ + NO3 --> 6.95329e-31 R2O2 + 6.95329e-31 RNO3 + 6.95329e-31 RCHO + 6.95329e-31 RO2_R', &
     '           SESQ + O3P --> 6.95329e-31 RCHO + 6.95329e-31 PROD2                                      ', &
     '            C2H6 + OH --> PSD1 + CCHO + RO2_R                                                       ', &
     '            C3H8 + OH --> PSD1 + 6.95329e-31 ACET + 6.95329e-31 RCHO + 6.95329e-31 RO2_R + 6.95329e-', &
     '            C2H2 + OH --> 6.95329e-31 HCOOH + PSD1 + 6.95329e-31 CO + 6.95329e-31 GLY + 6.95329e-31 ', &
     '            ALK3 + OH --> PSD1 + 6.95329e-31 TBU_O + 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-', &
     '            ALK4 + OH --> PSD1 + 6.95329e-31 CO + 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-31 ', &
     '            ALK5 + OH --> PSD1 + 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-31 CCHO + 6.95329e-3', &
     '            ARO1 + OH --> PSD1 + 6.95329e-31 DCB2 + 6.95329e-31 DCB3 + 6.95329e-31 CRES + 6.95329e-3', &
     '            ARO2 + OH --> PSD1 + 6.95329e-31 BACL + 6.95329e-31 DCB2 + 6.95329e-31 DCB3 + 6.95329e-3', &
     '            OLE1 + OH --> PSD1 + 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-31 CCHO + 6.95329e-3' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '            OLE1 + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 CCO_OH + 6.95329e-31 RCO_OH + 6.95329e-31 ', &
     '           OLE1 + NO3 --> 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-31 CCHO + 6.95329e-31 RNO3 ', &
     '           OLE1 + O3P --> 6.95329e-31 RCHO + 6.95329e-31 MEK + 6.95329e-31 PROD2                    ', &
     '            OLE2 + OH --> PSD1 + 6.95329e-31 BALD + 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-3', &
     '            OLE2 + O3 --> 6.95329e-31 HCOOH + 6.95329e-31 CCO_OH + 6.95329e-31 RCO_OH + 6.95329e-31 ', &
     '           OLE2 + NO3 --> 6.95329e-31 BALD + 6.95329e-31 ACET + 6.95329e-31 R2O2 + 6.95329e-31 CCHO ', &
     '           OLE2 + O3P --> 6.95329e-31 CO + 6.95329e-31 METHACRO + 6.95329e-31 RCHO + 6.95329e-31 MEK', &
     '            C2H2 + O3 --> 6.95329e-31 CO2 + 6.95329e-31 CO + 6.95329e-31 HO2 + 6.95329e-31 OH       ', &
     '            C3H6 + OH --> 6.95329e-31 XC + PSD1 + 6.95329e-31 CCHO + 6.95329e-31 HCHO + 6.95329e-31 ', &
     '            C3H6 + O3 --> 6.95329e-31 CO2 + 6.95329e-31 HCOOH + 6.95329e-31 CCO_OH + 6.95329e-31 XC ', &
     '           C3H6 + NO3 --> XN + 6.95329e-31 XC + 6.95329e-31 RO2_R + 6.95329e-31 RO2_N               ', &
     '           C3H6 + O3P --> 6.95329e-31 XC + 6.95329e-31 RCHO + 6.95329e-31 MEK                       ', &
     '                  SO2 --> H2SO4                                                                     ', &
     '                  HO2 -->                                                                           ', &
     '                  SO2 -->                                                                           ', &
     '                H2SO4 -->                                                                           ', &
     '                 HNO3 -->                                                                           ', &
     '                 H2O2 -->                                                                           ', &
     '                  CO2 -->                                                                           ', &
     '            ALK4 + OH --> ANT1_c + ALK4 + OH                                                        ', &
     '            ALK5 + OH --> ANT1_c + ALK5 + OH                                                        ', &
     '            OLE1 + OH --> ANT1_c + OLE1 + OH                                                        ', &
     '            OLE2 + OH --> ANT1_c + OLE2 + OH                                                        ', &
     '            ARO1 + OH --> ANT1_o + ARO1 + OH                                                        ', &
     '            ARO2 + OH --> ANT1_o + ARO2 + OH                                                        ', &
     '        ISOPRENE + OH --> BIOG1_c + ISOPRENE + OH                                                   ', &
     '            TERP + OH --> BIOG1_o + TERP + OH                                                       ', &
     '            SESQ + OH --> BIOG1_o + SESQ + OH                                                       ', &
     '        PCG1_B_C + OH --> PCG1_B_C + PSD2                                                           ', &
     '        PCG1_B_O + OH --> PCG1_B_O + PSD2 + OH                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(10) :: EQN_NAMES_8 = (/ &
     '       OPCG1_B_C + OH --> PSD2 + OPCG1_B_C                                                          ', &
     '       OPCG1_B_O + OH --> PSD2 + OPCG1_B_O + OH                                                     ', &
     '        PCG1_F_C + OH --> PCG1_F_C + PSD2                                                           ', &
     '        PCG1_F_O + OH --> PCG1_F_O + PSD2 + OH                                                      ', &
     '       OPCG1_F_C + OH --> PSD2 + OPCG1_F_C                                                          ', &
     '       OPCG1_F_O + OH --> PSD2 + OPCG1_F_O + OH                                                     ', &
     '        PCG2_B_C + OH --> PSD2 + 6.95329e-31 OPCG1_B_O + OPCG1_B_C                                  ', &
     '        PCG2_B_O + OH --> PSD2 + OPCG1_B_O + OH                                                     ', &
     '        PCG2_F_C + OH --> PSD2 + 6.95329e-31 OPCG1_F_O + OPCG1_F_C                                  ', &
     '        PCG2_F_O + OH --> PSD2 + OPCG1_F_O + OH                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(250) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8 /)

! INLINED global variables

! End INLINED global variables


END MODULE saprc99_mosaic_4bin_vbs2_Monitor
