! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : radm2sorg_Monitor.f90
! Time                 : Mon Sep 26 23:37:47 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/radm2sorg
! Equation file        : radm2sorg.kpp
! Output root filename : radm2sorg
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE radm2sorg_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(61) :: SPC_NAMES = (/ &
     'SULF        ','ORA1        ','ORA2        ', &
     'CO2         ','SO2         ','ETH         ', &
     'O1D         ','HC5         ','HC8         ', &
     'TOL         ','XYL         ','TPAN        ', &
     'HONO        ','H2O2        ','N2O5        ', &
     'HC3         ','CH4         ','PAA         ', &
     'O3P         ','HNO4        ','OP1         ', &
     'CSL         ','PAN         ','OL2         ', &
     'HNO3        ','CO          ','ISO         ', &
     'OLT         ','OLI         ','DCB         ', &
     'GLY         ','XNO2        ','KET         ', &
     'MGLY        ','TOLP        ','XYLP        ', &
     'OLTP        ','OLN         ','XO2         ', &
     'OL2P        ','HC5P        ','OP2         ', &
     'HCHO        ','HC8P        ','TCO3        ', &
     'O3          ','ONIT        ','ALD         ', &
     'OLIP        ','KETP        ','HO2         ', &
     'MO2         ','OH          ','NO3         ', &
     'ACO3        ','HC3P        ','ETHP        ', &
     'NO          ','NO2         ','H2O         ', &
     'M           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '                  NO2 --> O3P + NO                                                                  ', &
     '                   O3 --> O1D                                                                       ', &
     '                   O3 --> O3P                                                                       ', &
     '                 HONO --> OH + NO                                                                   ', &
     '                 HNO3 --> OH + NO2                                                                  ', &
     '                 HNO4 --> 6.95322e-31 HO2 + 6.95322e-31 OH + 6.95322e-31 NO3 + 6.95322e-31 NO2      ', &
     '                  NO3 --> NO                                                                        ', &
     '                  NO3 --> O3P + NO2                                                                 ', &
     '                 H2O2 --> 6.95322e-31 OH                                                            ', &
     '                 HCHO --> CO                                                                        ', &
     '                 HCHO --> CO + 6.95322e-31 HO2                                                      ', &
     '                  ALD --> CO + HO2 + MO2                                                            ', &
     '                  OP1 --> HCHO + HO2 + OH                                                           ', &
     '                  OP2 --> ALD + HO2 + OH                                                            ', &
     '                  PAA --> MO2 + OH                                                                  ', &
     '                  KET --> ACO3 + ETHP                                                               ', &
     '                  GLY --> 6.95322e-31 CO + 6.95322e-31 HCHO                                         ', &
     '                  GLY --> 6.95322e-31 CO + 6.95322e-31 HCHO + 6.95322e-31 HO2                       ', &
     '                 MGLY --> CO + HO2 + ACO3                                                           ', &
     '                  DCB --> TCO3 + HO2                                                                ', &
     '                 ONIT --> 6.95322e-31 KET + 6.95322e-31 ALD + HO2 + NO2                             ', &
     '              O3P + M --> O3                                                                        ', &
     '            O3P + NO2 --> NO                                                                        ', &
     '              O1D + M --> O3P                                                                       ', &
     '            O1D + H2O --> 6.95322e-31 OH                                                            ', &
     '              O3 + NO --> NO2                                                                       ', &
     '              O3 + OH --> HO2                                                                       ', &
     '             O3 + HO2 --> OH                                                                        ', &
     '             HO2 + NO --> OH + NO2                                                                  ', &
     '            HO2 + NO2 --> HNO4                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '                 HNO4 --> HO2 + NO2                                                                 ', &
     '      6.95322e-31 HO2 --> H2O2                                                                      ', &
     '6.95322e-31 HO2 + H2O --> H2O2                                                                      ', &
     '            H2O2 + OH --> HO2 + H2O                                                                 ', &
     '              OH + NO --> HONO                                                                      ', &
     '   6.95322e-31 NO + M --> 6.95322e-31 NO2                                                           ', &
     '             O3 + NO2 --> NO3                                                                       ', &
     '             NO3 + NO --> 6.95322e-31 NO2                                                           ', &
     '            NO3 + NO2 --> NO + NO2                                                                  ', &
     '            HO2 + NO3 --> HNO3                                                                      ', &
     '            NO3 + NO2 --> N2O5                                                                      ', &
     '                 N2O5 --> NO3 + NO2                                                                 ', &
     '                 N2O5 --> 6.95322e-31 HNO3                                                          ', &
     '             OH + NO2 --> HNO3                                                                      ', &
     '            HNO3 + OH --> NO3 + H2O                                                                 ', &
     '            HNO4 + OH --> NO2 + H2O                                                                 ', &
     '             HO2 + OH --> H2O                                                                       ', &
     '             SO2 + OH --> SULF + HO2                                                                ', &
     '              CO + OH --> CO2 + HO2                                                                 ', &
     '             CH4 + OH --> MO2 + H2O                                                                 ', &
     '             ETH + OH --> ETHP + H2O                                                                ', &
     '             HC3 + OH --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ALD + 6.95322e-31 HO2 + 6', &
     '             HC5 + OH --> 6.95322e-31 XO2 + HC5P + H2O                                              ', &
     '             HC8 + OH --> 6.95322e-31 XO2 + HC8P + H2O                                              ', &
     '             OL2 + OH --> OL2P                                                                      ', &
     '             OLT + OH --> OLTP                                                                      ', &
     '             OLI + OH --> OLIP                                                                      ', &
     '             TOL + OH --> 6.95322e-31 CSL + 6.95322e-31 TOLP + 6.95322e-31 HO2                      ', &
     '             XYL + OH --> 6.95322e-31 CSL + 6.95322e-31 XYLP + 6.95322e-31 HO2                      ', &
     '             CSL + OH --> 6.95322e-31 XO2 + 6.95322e-31 TCO3 + 6.95322e-31 HO2 - 6.95322e-31 OH     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '            HCHO + OH --> CO + HO2 + H2O                                                            ', &
     '             ALD + OH --> ACO3 + H2O                                                                ', &
     '             KET + OH --> KETP + H2O                                                                ', &
     '             GLY + OH --> 6.95322e-31 CO + HO2 + H2O                                                ', &
     '            MGLY + OH --> CO + ACO3 + H2O                                                           ', &
     '             DCB + OH --> TCO3 + H2O                                                                ', &
     '             OP1 + OH --> 6.95322e-31 HCHO + 6.95322e-31 MO2 + 6.95322e-31 OH                       ', &
     '             OP2 + OH --> 6.95322e-31 ALD + 6.95322e-31 OH + 6.95322e-31 HC3P                       ', &
     '             PAA + OH --> ACO3 + H2O                                                                ', &
     '             PAN + OH --> XO2 + HCHO + NO3                                                          ', &
     '            ONIT + OH --> HC3P + NO2                                                                ', &
     '             ISO + OH --> OLTP                                                                      ', &
     '           ACO3 + NO2 --> PAN                                                                       ', &
     '                  PAN --> ACO3 + NO2                                                                ', &
     '           TCO3 + NO2 --> TPAN                                                                      ', &
     '                 TPAN --> TCO3 + NO2                                                                ', &
     '             MO2 + NO --> HCHO + HO2 + NO2                                                          ', &
     '            HC3P + NO --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ONIT + 6.95322e-31 ALD + ', &
     '            HC5P + NO --> 6.95322e-31 KET + 6.95322e-31 ONIT + 6.95322e-31 ALD + 6.95322e-31 HO2 + 6', &
     '            HC8P + NO --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ONIT + 6.95322e-31 ALD + ', &
     '            OL2P + NO --> 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2 + NO2                            ', &
     '            OLTP + NO --> HCHO + ALD + HO2 + NO2                                                    ', &
     '            OLIP + NO --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2 + NO2          ', &
     '            ACO3 + NO --> MO2 + NO2                                                                 ', &
     '            TCO3 + NO --> 6.95322e-31 CO + 6.95322e-31 GLY + 6.95322e-31 MGLY + 6.95322e-31 XO2 + 6.', &
     '            TOLP + NO --> 6.95322e-31 DCB + 6.95322e-31 GLY + 6.95322e-31 MGLY + HO2 + NO2          ', &
     '            XYLP + NO --> 6.95322e-31 DCB + 6.95322e-31 MGLY + HO2 + NO2                            ', &
     '            ETHP + NO --> ALD + HO2 + NO2                                                           ', &
     '            KETP + NO --> MGLY + HO2 + NO2                                                          ', &
     '             OLN + NO --> HCHO + ALD + 6.95322e-31 NO2                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '           HCHO + NO3 --> HNO3 + CO + HO2                                                           ', &
     '            ALD + NO3 --> HNO3 + ACO3                                                               ', &
     '            GLY + NO3 --> HNO3 + 6.95322e-31 CO + HO2                                               ', &
     '           MGLY + NO3 --> HNO3 + CO + ACO3                                                          ', &
     '            DCB + NO3 --> HNO3 + TCO3                                                               ', &
     '            CSL + NO3 --> 6.95322e-31 CSL + HNO3 + XNO2                                             ', &
     '            OL2 + NO3 --> OLN                                                                       ', &
     '            OLT + NO3 --> OLN                                                                       ', &
     '            OLI + NO3 --> OLN                                                                       ', &
     '            ISO + NO3 --> OLN                                                                       ', &
     '             OL2 + O3 --> 6.95322e-31 ORA1 + 6.95322e-31 CO + HCHO + 6.95322e-31 HO2                ', &
     '             OLT + O3 --> 6.95322e-31 ORA1 + 6.95322e-31 ORA2 + 6.95322e-31 CH4 + 6.95322e-31 CO + 6', &
     '             OLI + O3 --> 6.95322e-31 ORA1 + 6.95322e-31 ORA2 + 6.95322e-31 CH4 + 6.95322e-31 CO + 6', &
     '             ISO + O3 --> 6.95322e-31 ORA1 + 6.95322e-31 ORA2 + 6.95322e-31 CO + 6.95322e-31 HCHO + ', &
     '            HO2 + MO2 --> OP1                                                                       ', &
     '           HO2 + ETHP --> OP2                                                                       ', &
     '           HO2 + HC3P --> OP2                                                                       ', &
     '           HC5P + HO2 --> OP2                                                                       ', &
     '           HC8P + HO2 --> OP2                                                                       ', &
     '           OL2P + HO2 --> OP2                                                                       ', &
     '           OLTP + HO2 --> OP2                                                                       ', &
     '           OLIP + HO2 --> OP2                                                                       ', &
     '           KETP + HO2 --> OP2                                                                       ', &
     '           HO2 + ACO3 --> PAA                                                                       ', &
     '           TOLP + HO2 --> OP2                                                                       ', &
     '           XYLP + HO2 --> OP2                                                                       ', &
     '           TCO3 + HO2 --> OP2                                                                       ', &
     '            OLN + HO2 --> ONIT                                                                      ', &
     '      6.95322e-31 MO2 --> 6.95322e-31 HCHO + HO2                                                    ', &
     '           MO2 + ETHP --> 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '           MO2 + HC3P --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2                ', &
     '           HC5P + MO2 --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2                ', &
     '           HC8P + MO2 --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2                ', &
     '           OL2P + MO2 --> 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2                                  ', &
     '           OLTP + MO2 --> 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2                                  ', &
     '           OLIP + MO2 --> 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ALD + HO2                ', &
     '           KETP + MO2 --> 6.95322e-31 MGLY + 6.95322e-31 HCHO + HO2                                 ', &
     '           MO2 + ACO3 --> 6.95322e-31 ORA2 + HCHO + 6.95322e-31 HO2 + 6.95322e-31 MO2               ', &
     '           TOLP + MO2 --> 6.95322e-31 DCB + 6.95322e-31 GLY + 6.95322e-31 MGLY + HCHO + 6.95322e-31 ', &
     '           XYLP + MO2 --> 6.95322e-31 DCB + 6.95322e-31 MGLY + HCHO + 6.95322e-31 HO2               ', &
     '           TCO3 + MO2 --> 6.95322e-31 ORA2 + 6.95322e-31 CO + 6.95322e-31 GLY + 6.95322e-31 MGLY + X', &
     '          ACO3 + ETHP --> 6.95322e-31 ORA2 + ALD + 6.95322e-31 HO2 + 6.95322e-31 MO2                ', &
     '          ACO3 + HC3P --> 6.95322e-31 ORA2 + 6.95322e-31 KET + 6.95322e-31 ALD + 6.95322e-31 HO2 + 6', &
     '          HC5P + ACO3 --> 6.95322e-31 ORA2 + 6.95322e-31 KET + 6.95322e-31 ALD + 6.95322e-31 HO2 + 6', &
     '          HC8P + ACO3 --> 6.95322e-31 ORA2 + 6.95322e-31 KET + 6.95322e-31 ALD + 6.95322e-31 HO2 + 6', &
     '          OL2P + ACO3 --> 6.95322e-31 ORA2 + 6.95322e-31 HCHO + 6.95322e-31 ALD + 6.95322e-31 HO2 + ', &
     '          OLTP + ACO3 --> 6.95322e-31 ORA2 + 6.95322e-31 HCHO + ALD + 6.95322e-31 HO2 + 6.95322e-31 ', &
     '          OLIP + ACO3 --> 6.95322e-31 ORA2 + 6.95322e-31 KET + 6.95322e-31 HCHO + 6.95322e-31 ALD + ', &
     '          KETP + ACO3 --> 6.95322e-31 ORA2 + MGLY + 6.95322e-31 HO2 + 6.95322e-31 MO2               ', &
     '     6.95322e-31 ACO3 --> 6.95322e-31 MO2                                                           ', &
     '          TOLP + ACO3 --> DCB + 6.95322e-31 GLY + 6.95322e-31 MGLY + HO2 + MO2                      ', &
     '          XYLP + ACO3 --> DCB + MGLY + HO2 + MO2                                                    ', &
     '          TCO3 + ACO3 --> 6.95322e-31 CO + 6.95322e-31 GLY + 6.95322e-31 MGLY + 6.95322e-31 XO2 + 6.', &
     '            XO2 + HO2 --> OP2                                                                       ', &
     '            XO2 + MO2 --> HCHO + HO2                                                                ', &
     '           XO2 + ACO3 --> MO2                                                                       ', &
     '      6.95322e-31 XO2 --> H2O                                                                       ', &
     '             XO2 + NO --> NO2                                                                       ', &
     '           XNO2 + NO2 --> ONIT                                                                      ', &
     '           XNO2 + HO2 --> OP2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(6) :: EQN_NAMES_5 = (/ &
     '           XNO2 + MO2 --> HCHO + HO2                                                                ', &
     '          XNO2 + ACO3 --> MO2                                                                       ', &
     '     6.95322e-31 XNO2 --> H2O                                                                       ', &
     '            OLN + MO2 --> 6.95322e-31 HCHO + ALD + 6.95322e-31 HO2 + NO2                            ', &
     '           OLN + ACO3 --> 6.95322e-31 ORA2 + HCHO + ALD + 6.95322e-31 MO2 + NO2                     ', &
     '      6.95322e-31 OLN --> 6.95322e-31 HCHO + 6.95322e-31 ALD + 6.95322e-31 NO2                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(156) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5 /)

! INLINED global variables

! End INLINED global variables


END MODULE radm2sorg_Monitor
