! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : nmhc9_Monitor.f90
! Time                 : Mon Sep 26 23:37:20 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/nmhc9
! Equation file        : nmhc9.kpp
! Output root filename : nmhc9
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE nmhc9_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(59) :: SPC_NAMES = (/ &
     'C2H6        ','C4H10       ','MeCOCO      ', &
     'C3H8        ','N2O5        ','MeO2NO2     ', &
     'NACA        ','H2O2        ','PAA         ', &
     'CH3COOH     ','ISOOH       ','MeOOH       ', &
     'PAN         ','MPAN        ','HCOOH       ', &
     'EtOOH       ','PrOOH       ','PrONO2      ', &
     'C2H4        ','MEKOOH      ','O1D         ', &
     'HNO4        ','ACETP       ','CH4         ', &
     'HNO3        ','C3H6OOH     ','C4H9OOH     ', &
     'ACET        ','MVKOOH      ','MEK         ', &
     'CO          ','MeOH        ','ISON        ', &
     'PrO2        ','MGLO        ','ACETO2      ', &
     'C3H6        ','ISOP        ','ACETOL      ', &
     'C3H6O2      ','MVK         ','MEKO2       ', &
     'C4H9O2      ','ONIT        ','HCHO        ', &
     'ALD         ','EtO2        ','ISO2        ', &
     'MVKO2       ','MeO2        ','PA          ', &
     'NO3         ','O3          ','NO2         ', &
     'OH          ','NO          ','HO2         ', &
     'H2O         ','M           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '               O3 --> O1D                                                                           ', &
     '          O1D + M --> O3                                                                            ', &
     '        O1D + H2O --> 6.95289e-31 OH                                                                ', &
     '                M --> 6.95289e-31 O3                                                                ', &
     '          O3 + OH --> HO2                                                                           ', &
     '         O3 + HO2 --> OH                                                                            ', &
     '         OH + HO2 --> H2O                                                                           ', &
     '  6.95289e-31 HO2 --> H2O2                                                                          ', &
     '             H2O2 --> 6.95289e-31 OH                                                                ', &
     '        H2O2 + OH --> HO2                                                                           ', &
     '          CO + OH --> HO2                                                                           ', &
     '         CH4 + OH --> MeO2 + H2O                                                                    ', &
     '        O1D + CH4 --> 6.95289e-31 HCHO + 6.95289e-31 MeO2 + 6.95289e-31 OH + 6.95289e-31 HO2        ', &
     '       MeO2 + HO2 --> MeOOH                                                                         ', &
     '       MeO2 + HO2 --> HCHO + H2O                                                                    ', &
     '        MeO2 + NO --> HCHO + NO2 + HO2                                                              ', &
     ' 6.95289e-31 MeO2 --> 6.95289e-31 HCHO + 6.95289e-31 HO2                                            ', &
     ' 6.95289e-31 MeO2 --> MeOH + HCHO                                                                   ', &
     '       MeO2 + NO3 --> HCHO + NO2 + HO2                                                              ', &
     '            MeOOH --> HCHO + OH + HO2                                                               ', &
     '       MeOOH + OH --> 6.95289e-31 HCHO + 6.95289e-31 MeO2 + 6.95289e-31 OH                          ', &
     '             HCHO --> CO + 6.95289e-31 HO2                                                          ', &
     '             HCHO --> CO                                                                            ', &
     '        HCHO + OH --> CO + HO2 + H2O                                                                ', &
     '       HCHO + NO3 --> HNO3 + CO + HO2                                                               ', &
     '          O3 + NO --> NO2                                                                           ', &
     '         NO + HO2 --> NO2 + OH                                                                      ', &
     '              NO2 --> O3 + NO                                                                       ', &
     '         O3 + NO2 --> NO3                                                                           ', &
     '         NO2 + OH --> HNO3                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '        NO2 + HO2 --> HNO4                                                                          ', &
     '             HNO3 --> NO2 + OH                                                                      ', &
     '        HNO3 + OH --> NO3                                                                           ', &
     '              NO3 --> O3 + NO2                                                                      ', &
     '              NO3 --> NO                                                                            ', &
     '         NO3 + NO --> 6.95289e-31 NO2                                                               ', &
     '        NO3 + NO2 --> N2O5                                                                          ', &
     '        NO3 + HO2 --> NO2 + OH                                                                      ', &
     '             N2O5 --> NO3 + NO2                                                                     ', &
     '             N2O5 --> NO3 + NO2                                                                     ', &
     '             N2O5 --> 6.95289e-31 HNO3                                                              ', &
     '       N2O5 + H2O --> 6.95289e-31 HNO3                                                              ', &
     '             HNO4 --> 6.95289e-31 NO3 + 6.95289e-31 NO2 + 6.95289e-31 OH + 6.95289e-31 HO2          ', &
     '             HNO4 --> NO2 + HO2                                                                     ', &
     '        HNO4 + OH --> NO2 + H2O                                                                     ', &
     '           OH + M --> HO2 + H2O                                                                     ', &
     '        MeOH + OH --> HCHO + HO2                                                                    ', &
     '       MeO2 + NO2 --> MeO2NO2                                                                       ', &
     '          MeO2NO2 --> MeO2 + NO2                                                                    ', &
     '          MeO2NO2 --> 6.95289e-31 HCHO + 6.95289e-31 MeO2 + 6.95289e-31 NO3 + 6.95289e-31 NO2       ', &
     '        ISOP + OH --> ISO2                                                                          ', &
     '       ISOP + NO3 --> ISON                                                                          ', &
     '        ISOP + O3 --> 6.95289e-31 H2O2 + 6.95289e-31 HCOOH + 6.95289e-31 CO + 6.95289e-31 MVK + 6.95', &
     '       ISO2 + HO2 --> ISOOH                                                                         ', &
     '        ISO2 + NO --> 6.95289e-31 ISON + 6.95289e-31 MVK + 6.95289e-31 HCHO + 6.95289e-31 NO2 + 6.95', &
     '            ISOOH --> MVK + HCHO + OH + HO2                                                         ', &
     '       ISOOH + OH --> MVK + OH                                                                      ', &
     '         MVK + OH --> MVKO2                                                                         ', &
     '              MVK --> CO + HCHO + PA + HO2                                                          ', &
     '         MVK + O3 --> 6.95289e-31 HCOOH + 6.95289e-31 CO + 6.95289e-31 MGLO + 6.95289e-31 PA + 6.952' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '       MVKO2 + NO --> 6.95289e-31 CO + 6.95289e-31 MGLO + 6.95289e-31 ACETOL + 6.95289e-31 HCHO + 6.', &
     '      MVKO2 + HO2 --> MVKOOH                                                                        ', &
     '           MVKOOH --> 6.95289e-31 CO + 6.95289e-31 MGLO + 6.95289e-31 ACETOL + 6.95289e-31 HCHO + 6.', &
     '      MVKOOH + OH --> MVKO2                                                                         ', &
     '        ISON + OH --> NACA + ACETOL                                                                 ', &
     '             ISON --> MVK + HCHO + NO2 + HO2                                                        ', &
     '      MVKO2 + NO2 --> MPAN                                                                          ', &
     ' 6.95289e-31 ISO2 --> 6.95289e-31 MVK + HCHO + HO2                                                  ', &
     '6.95289e-31 MVKO2 --> 6.95289e-31 CO + MGLO + ACETOL + 6.95289e-31 HCHO + HO2                       ', &
     '      ISO2 + MeO2 --> 6.95289e-31 MeOH + 6.95289e-31 MGLO + 6.95289e-31 ACETOL + 6.95289e-31 MVK + 6', &
     '     MVKO2 + MeO2 --> 6.95289e-31 CO + 6.95289e-31 MeOH + 6.95289e-31 MGLO + 6.95289e-31 ACETOL + 6.', &
     '        MGLO + OH --> CO + PA                                                                       ', &
     '             MGLO --> CO + PA + HO2                                                                 ', &
     '      ACETOL + OH --> MGLO + HO2                                                                    ', &
     '           ACETOL --> HCHO + PA + HO2                                                               ', &
     '         PA + HO2 --> PAA                                                                           ', &
     '         PA + HO2 --> CH3COOH + O3                                                                  ', &
     '          PA + NO --> MeO2 + NO2                                                                    ', &
     '         PA + NO2 --> PAN                                                                           ', &
     '        MeO2 + PA --> HCHO + MeO2 + HO2                                                             ', &
     '        MeO2 + PA --> CH3COOH + HCHO                                                                ', &
     '   6.95289e-31 PA --> 6.95289e-31 MeO2                                                              ', &
     '         PA + NO3 --> MeO2 + NO2                                                                    ', &
     '              PAA --> MeO2 + OH                                                                     ', &
     '         PAA + OH --> PA                                                                            ', &
     '         PAN + OH --> HCHO + NO2                                                                    ', &
     '              PAN --> PA + NO2                                                                      ', &
     '              PAN --> PA + NO2                                                                      ', &
     '        MPAN + OH --> ACETOL + NO2                                                                  ', &
     '             MPAN --> MVKO2 + NO2                                                                   ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '             MPAN --> ACETOL + NO2                                                                  ', &
     '     CH3COOH + OH --> MeO2 + H2O                                                                    ', &
     '       HCOOH + OH --> HO2                                                                           ', &
     '        NACA + OH --> CO + HCHO + NO2                                                               ', &
     '             NACA --> CO + HCHO + NO2                                                               ', &
     '        C2H6 + OH --> EtO2 + H2O                                                                    ', &
     '       EtO2 + HO2 --> EtOOH                                                                         ', &
     '      EtO2 + MeO2 --> 6.95289e-31 MeOH + 6.95289e-31 HCHO + 6.95289e-31 ALD + HO2                   ', &
     '        EtO2 + PA --> 6.95289e-31 CH3COOH + ALD + 6.95289e-31 MeO2 + 6.95289e-31 HO2                ', &
     '        EtO2 + NO --> ALD + NO2 + HO2                                                               ', &
     '       EtO2 + NO3 --> ALD + NO2 + HO2                                                               ', &
     '         ALD + OH --> PA + H2O                                                                      ', &
     '              ALD --> CO + MeO2 + HO2                                                               ', &
     '        ALD + NO3 --> HNO3 + PA                                                                     ', &
     '            EtOOH --> ALD + OH + HO2                                                                ', &
     '       EtOOH + OH --> 6.95289e-31 ALD + 6.95289e-31 EtO2 + 6.95289e-31 OH                           ', &
     '        C3H8 + OH --> 6.95289e-31 PrO2 + 6.95289e-31 EtO2 + H2O                                     ', &
     '        PrO2 + NO --> 6.95289e-31 PrONO2 + 6.95289e-31 ACET + 6.95289e-31 NO2 + 6.95289e-31 HO2     ', &
     '       PrO2 + HO2 --> PrOOH                                                                         ', &
     '      PrO2 + MeO2 --> ACET + 6.95289e-31 MeOH + 6.95289e-31 HCHO + 6.95289e-31 HO2                  ', &
     '            PrOOH --> ACET + OH + HO2                                                               ', &
     '       PrOOH + OH --> 6.95289e-31 ACET + 6.95289e-31 PrO2 + 6.95289e-31 OH                          ', &
     '           PrONO2 --> ACET + NO2 + HO2                                                              ', &
     '      PrONO2 + OH --> ACET + NO2                                                                    ', &
     '        ACET + OH --> ACETO2 + H2O                                                                  ', &
     '             ACET --> MeO2 + PA                                                                     ', &
     '      ACETO2 + NO --> HCHO + PA + NO2                                                               ', &
     '     ACETO2 + HO2 --> ACETP                                                                         ', &
     '    ACETO2 + MeO2 --> 6.95289e-31 MeOH + 6.95289e-31 MGLO + 6.95289e-31 ACETOL + 6.95289e-31 HCHO + ', &
     '       ACETP + OH --> 6.95289e-31 MGLO + 6.95289e-31 ACETO2 + 6.95289e-31 OH                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(25) :: EQN_NAMES_4 = (/ &
     '            ACETP --> PA + OH + HO2                                                                 ', &
     '        C3H6 + OH --> C3H6O2                                                                        ', &
     '        C3H6 + O3 --> 6.95289e-31 HCOOH + 6.95289e-31 CH4 + 6.95289e-31 CO + 6.95289e-31 MeOH + 6.95', &
     '       C3H6 + NO3 --> ONIT                                                                          ', &
     '      C3H6O2 + NO --> 6.95289e-31 ONIT + 6.95289e-31 HCHO + 6.95289e-31 ALD + 6.95289e-31 NO2 + 6.95', &
     '     C3H6O2 + HO2 --> C3H6OOH                                                                       ', &
     '     C3H6OOH + OH --> 6.95289e-31 ACETOL + 6.95289e-31 C3H6O2 + 6.95289e-31 OH + H2O                ', &
     '          C3H6OOH --> HCHO + ALD + OH + HO2                                                         ', &
     '        C2H4 + OH --> 6.95289e-31 C3H6O2                                                            ', &
     '        C2H4 + O3 --> 6.95289e-31 HCOOH + 6.95289e-31 CO + HCHO + 6.95289e-31 OH + 6.95289e-31 HO2  ', &
     '       C4H10 + OH --> C4H9O2 + H2O                                                                  ', &
     '      C4H9O2 + NO --> 6.95289e-31 MEK + 6.95289e-31 ONIT + 6.95289e-31 ALD + 6.95289e-31 EtO2 + 6.95', &
     '     C4H9O2 + HO2 --> C4H9OOH                                                                       ', &
     '    C4H9O2 + MeO2 --> 6.95289e-31 MEK + 6.95289e-31 MeOH + 6.95289e-31 HCHO + 6.95289e-31 ALD + 6.95', &
     '     C4H9OOH + OH --> 6.95289e-31 MEK + 6.95289e-31 C4H9O2 + 6.95289e-31 OH + 6.95289e-31 H2O       ', &
     '          C4H9OOH --> 6.95289e-31 MEK + 6.95289e-31 ALD + 6.95289e-31 EtO2 + OH + 6.95289e-31 HO2   ', &
     '              MEK --> EtO2 + PA                                                                     ', &
     '         MEK + OH --> MEKO2                                                                         ', &
     '       MEKO2 + NO --> 6.95289e-31 ONIT + 6.95289e-31 ALD + 6.95289e-31 PA + 6.95289e-31 NO2         ', &
     '      MEKO2 + HO2 --> MEKOOH                                                                        ', &
     '      MEKOOH + OH --> 6.95289e-31 MeCOCO + 6.95289e-31 MEKO2 + 6.95289e-31 OH                       ', &
     '           MEKOOH --> ALD + PA + OH                                                                 ', &
     '           MeCOCO --> 6.95289e-31 PA                                                                ', &
     '        ONIT + OH --> MEK + NO2                                                                     ', &
     '             ONIT --> 6.95289e-31 MEK + 6.95289e-31 ALD + 6.95289e-31 EtO2 + NO2 + 6.95289e-31 HO2  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(145) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4 /)

! INLINED global variables

! End INLINED global variables


END MODULE nmhc9_Monitor
