! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm4_Monitor.f90
! Time                 : Mon Sep 26 23:36:54 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/cbm4
! Equation file        : cbm4.kpp
! Output root filename : cbm4
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm4_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(33) :: SPC_NAMES = (/ &
     'O1D_CB4     ','H2O2        ','PAN         ', &
     'CRO         ','TOL         ','N2O5        ', &
     'XYL         ','XO2N        ','HONO        ', &
     'PNA         ','TO2         ','HNO3        ', &
     'ROR         ','CRES        ','MGLY        ', &
     'CO          ','ETH         ','XO2         ', &
     'OPEN        ','PAR         ','HCHO        ', &
     'ISOP        ','OLE         ','ALD2        ', &
     'O3          ','NO2         ','HO          ', &
     'HO2         ','O           ','NO3         ', &
     'NO          ','C2O3        ','H2O         ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '                  NO2 --> O + NO                                                                    ', &
     '                   O3 --> O                                                                         ', &
     '                   O3 --> O1D_CB4                                                                   ', &
     '                  NO3 --> 6.95301e-31 NO2 + 6.95301e-31 O + 6.95301e-31 NO                          ', &
     '                 HONO --> HO + NO                                                                   ', &
     '                 H2O2 --> 6.95301e-31 HO                                                            ', &
     '                 HCHO --> CO + 6.95301e-31 HO2                                                      ', &
     '                 HCHO --> CO                                                                        ', &
     '                 ALD2 --> CO + XO2 + HCHO + 6.95301e-31 HO2                                         ', &
     '                 OPEN --> CO + HO2 + C2O3                                                           ', &
     '                 MGLY --> CO + HO2 + C2O3                                                           ', &
     '                    O --> O3                                                                        ', &
     '              O3 + NO --> NO2                                                                       ', &
     '              NO2 + O --> NO                                                                        ', &
     '              NO2 + O --> NO3                                                                       ', &
     '               O + NO --> NO2                                                                       ', &
     '             O3 + NO2 --> NO3                                                                       ', &
     '              O1D_CB4 --> O                                                                         ', &
     '        O1D_CB4 + H2O --> 6.95301e-31 HO                                                            ', &
     '              O3 + HO --> HO2                                                                       ', &
     '             O3 + HO2 --> HO                                                                        ', &
     '             NO3 + NO --> 6.95301e-31 NO2                                                           ', &
     '            NO2 + NO3 --> NO2 + NO                                                                  ', &
     '            NO2 + NO3 --> N2O5                                                                      ', &
     '           N2O5 + H2O --> 6.95301e-31 HNO3                                                          ', &
     '                 N2O5 --> NO2 + NO3                                                                 ', &
     '       6.95301e-31 NO --> 6.95301e-31 NO2                                                           ', &
     '       NO2 + NO + H2O --> 6.95301e-31 HONO                                                          ', &
     '              HO + NO --> HONO                                                                      ', &
     '            HONO + HO --> NO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '     6.95301e-31 HONO --> NO2 + NO                                                                  ', &
     '             NO2 + HO --> HNO3                                                                      ', &
     '            HNO3 + HO --> NO3                                                                       ', &
     '             HO2 + NO --> NO2 + HO                                                                  ', &
     '            NO2 + HO2 --> PNA                                                                       ', &
     '                  PNA --> NO2 + HO2                                                                 ', &
     '             PNA + HO --> NO2                                                                       ', &
     '      6.95301e-31 HO2 --> H2O2                                                                      ', &
     '6.95301e-31 HO2 + H2O --> H2O2                                                                      ', &
     '            H2O2 + HO --> HO2                                                                       ', &
     '              CO + HO --> HO2                                                                       ', &
     '            HCHO + HO --> CO + HO2                                                                  ', &
     '             HCHO + O --> CO + HO + HO2                                                             ', &
     '           HCHO + NO3 --> HNO3 + CO + HO2                                                           ', &
     '             ALD2 + O --> HO + C2O3                                                                 ', &
     '            ALD2 + HO --> C2O3                                                                      ', &
     '           ALD2 + NO3 --> HNO3 + C2O3                                                               ', &
     '            NO + C2O3 --> XO2 + HCHO + NO2 + HO2                                                    ', &
     '           NO2 + C2O3 --> PAN                                                                       ', &
     '                  PAN --> NO2 + C2O3                                                                ', &
     '     6.95301e-31 C2O3 --> 6.95301e-31 XO2 + 6.95301e-31 HCHO + 6.95301e-31 HO2                      ', &
     '           HO2 + C2O3 --> 6.95301e-31 XO2 + 6.95301e-31 HCHO + 6.95301e-31 HO + 6.95301e-31 HO2     ', &
     '                   HO --> XO2 + HCHO + HO2                                                          ', &
     '             PAR + HO --> 6.95301e-31 XO2N + 6.95301e-31 ROR + 6.95301e-31 XO2 - 6.95301e-31 PAR + 6', &
     '                  ROR --> 6.95301e-31 XO2N + 6.95301e-31 ROR + 6.95301e-31 XO2 - 6.95301e-31 PAR + 6', &
     '                  ROR --> HO2                                                                       ', &
     '            ROR + NO2 -->                                                                           ', &
     '              OLE + O --> 6.95301e-31 XO2N + 6.95301e-31 CO + 6.95301e-31 XO2 + 6.95301e-31 PAR + 6.', &
     '             OLE + HO --> XO2 - PAR + HCHO + ALD2 + HO2                                             ', &
     '             OLE + O3 --> 6.95301e-31 CO + 6.95301e-31 XO2 - PAR + 6.95301e-31 HCHO + 6.95301e-31 AL' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(21) :: EQN_NAMES_2 = (/ &
     '            OLE + NO3 --> 6.95301e-31 XO2N + 6.95301e-31 XO2 - PAR + HCHO + ALD2 + NO2              ', &
     '              ETH + O --> CO + 6.95301e-31 XO2 + HCHO + 6.95301e-31 HO + 6.95301e-31 HO2            ', &
     '             ETH + HO --> XO2 + 6.95301e-31 HCHO + 6.95301e-31 ALD2 + HO2                           ', &
     '             ETH + O3 --> 6.95301e-31 CO + HCHO + 6.95301e-31 HO2                                   ', &
     '             TOL + HO --> 6.95301e-31 TO2 + 6.95301e-31 CRES + 6.95301e-31 XO2 + 6.95301e-31 HO2    ', &
     '             TO2 + NO --> 6.95301e-31 OPEN + 6.95301e-31 NO2 + 6.95301e-31 HO2                      ', &
     '                  TO2 --> CRES + HO2                                                                ', &
     '            CRES + HO --> 6.95301e-31 CRO + 6.95301e-31 XO2 + 6.95301e-31 OPEN + 6.95301e-31 HO2    ', &
     '           CRES + NO3 --> CRO + HNO3                                                                ', &
     '            CRO + NO2 -->                                                                           ', &
     '             XYL + HO --> 6.95301e-31 TO2 + 6.95301e-31 CRES + 6.95301e-31 MGLY + 6.95301e-31 XO2 + ', &
     '            OPEN + HO --> 6.95301e-31 CO + XO2 + HCHO + 6.95301e-31 HO2 + C2O3                      ', &
     '            OPEN + O3 --> 6.95301e-31 MGLY + 6.95301e-31 CO + 6.95301e-31 XO2 + 6.95301e-31 HCHO + 6', &
     '            MGLY + HO --> XO2 + C2O3                                                                ', &
     '             ISOP + O --> 6.95301e-31 CO + 6.95301e-31 ETH + 6.95301e-31 XO2 + 6.95301e-31 PAR + 6.9', &
     '            ISOP + HO --> 6.95301e-31 XO2N + 6.95301e-31 MGLY + ETH + XO2 + HCHO + 6.95301e-31 ALD2 ', &
     '            ISOP + O3 --> 6.95301e-31 MGLY + 6.95301e-31 CO + 6.95301e-31 ETH + 6.95301e-31 PAR + HC', &
     '           ISOP + NO3 --> XO2N                                                                      ', &
     '             XO2 + NO --> NO2                                                                       ', &
     '      6.95301e-31 XO2 -->                                                                           ', &
     '            XO2N + NO -->                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(81) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2 /)

! INLINED global variables

! End INLINED global variables


END MODULE cbm4_Monitor
