! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbmz_bb_Monitor.f90
! Time                 : Mon Sep 26 23:36:56 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/cbmz_bb
! Equation file        : cbmz_bb.kpp
! Output root filename : cbmz_bb
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbmz_bb_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(58) :: SPC_NAMES = (/ &
     'H2SO4       ','HCl         ','NH3         ', &
     'HCOOH       ','RCOOH       ','O1D         ', &
     'SO2         ','ANOL        ','H2O2        ', &
     'PAN         ','TOL         ','N2O5        ', &
     'XYL         ','CH4         ','CRO         ', &
     'HNO4        ','C2H6        ','TO2         ', &
     'XPAR        ','CH3OOH      ','ETHOOH      ', &
     'HONO        ','C2H4        ','CH3OH       ', &
     'O3P         ','CRES        ','HNO3        ', &
     'CO          ','PAR         ','OPEN        ', &
     'ISOPN       ','ISOPP       ','ISOPO2      ', &
     'OLET        ','ISOP        ','HCHO        ', &
     'XO2         ','AONE        ','OLEI        ', &
     'ETHP        ','NAP         ','MGLY        ', &
     'ALD2        ','CH3O2       ','ISOPRD      ', &
     'ANO2        ','ROOH        ','RO2         ', &
     'ONIT        ','OH          ','O3          ', &
     'NO2         ','C2O3        ','NO3         ', &
     'HO2         ','NO          ','H2O         ', &
     'M           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '                  NO2 --> O3P + NO                                                                  ', &
     '                  NO3 --> 6.95319e-31 O3P + 6.95319e-31 NO2 + 6.95319e-31 NO                        ', &
     '                 HONO --> OH + NO                                                                   ', &
     '                 HNO3 --> OH + NO2                                                                  ', &
     '                 HNO4 --> NO2 + HO2                                                                 ', &
     '                 N2O5 --> NO2 + NO3                                                                 ', &
     '                   O3 --> O3P                                                                       ', &
     '                   O3 --> O1D                                                                       ', &
     '                 H2O2 --> 6.95319e-31 OH                                                            ', &
     '                 HCHO --> CO + 6.95319e-31 HO2                                                      ', &
     '                 HCHO --> CO                                                                        ', &
     '               CH3OOH --> HCHO + OH + HO2                                                           ', &
     '               ETHOOH --> ALD2 + OH + HO2                                                           ', &
     '                 ALD2 --> CO + CH3O2 + HO2                                                          ', &
     '                 AONE --> CH3O2 + C2O3                                                              ', &
     '                 MGLY --> CO + C2O3 + HO2                                                           ', &
     '                 OPEN --> CO + C2O3 + HO2                                                           ', &
     '                 ROOH --> 6.95319e-31 XPAR + 6.95319e-31 XO2 + 6.95319e-31 AONE + 6.95319e-31 ETHP +', &
     '                 ONIT --> 6.95319e-31 XPAR + 6.95319e-31 XO2 + 6.95319e-31 AONE + 6.95319e-31 ETHP +', &
     '               ISOPRD --> 6.95319e-31 CO + 6.95319e-31 HCHO + 6.95319e-31 AONE + 6.95319e-31 ALD2 + ', &
     '              O1D + M --> O3P                                                                       ', &
     '            O1D + H2O --> 6.95319e-31 OH                                                            ', &
     '              O3P + M --> O3                                                                        ', &
     '             O3P + O3 --> 6.95319e-31 M                                                             ', &
     '            O3P + NO2 --> NO                                                                        ', &
     '            O3P + NO2 --> NO3                                                                       ', &
     '             O3P + NO --> NO2                                                                       ', &
     '              O3 + NO --> NO2                                                                       ', &
     '             O3 + NO2 --> NO3                                                                       ', &
     '              OH + O3 --> HO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '             O3 + HO2 --> OH                                                                        ', &
     '               OH + M --> HO2 + H2O                                                                 ', &
     '              OH + NO --> HONO                                                                      ', &
     '             OH + NO2 --> HNO3                                                                      ', &
     '             OH + NO3 --> NO2 + HO2                                                                 ', &
     '            HONO + OH --> NO2                                                                       ', &
     '            HNO3 + OH --> NO3                                                                       ', &
     '            HNO4 + OH --> NO2                                                                       ', &
     '             OH + HO2 --> H2O + 6.95319e-31 M                                                       ', &
     '            H2O2 + OH --> HO2                                                                       ', &
     '      6.95319e-31 HO2 --> H2O2                                                                      ', &
     '6.95319e-31 HO2 + H2O --> H2O2                                                                      ', &
     '             HO2 + NO --> OH + NO2                                                                  ', &
     '            NO2 + HO2 --> HNO4                                                                      ', &
     '            NO2 + HO2 --> HONO                                                                      ', &
     '                 HNO4 --> NO2 + HO2                                                                 ', &
     '             NO3 + NO --> 6.95319e-31 NO2                                                           ', &
     '            NO2 + NO3 --> NO2 + NO                                                                  ', &
     '            NO2 + NO3 --> N2O5                                                                      ', &
     '      6.95319e-31 NO3 --> 6.95319e-31 NO2                                                           ', &
     '            NO3 + HO2 --> 6.95319e-31 HNO3 + 6.95319e-31 OH + 6.95319e-31 NO2                       ', &
     '           N2O5 + H2O --> 6.95319e-31 HNO3                                                          ', &
     '                 N2O5 --> NO2 + NO3                                                                 ', &
     '              CO + OH --> HO2                                                                       ', &
     '             SO2 + OH --> H2SO4 + HO2                                                               ', &
     '             CH4 + OH --> CH3O2                                                                     ', &
     '            C2H6 + OH --> ETHP                                                                      ', &
     '             PAR + OH --> RO2                                                                       ', &
     '            HCHO + OH --> CO + HO2                                                                  ', &
     '           HCHO + NO3 --> HNO3 + CO + HO2                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '            ALD2 + OH --> C2O3                                                                      ', &
     '           ALD2 + NO3 --> HNO3 + C2O3                                                               ', &
     '            AONE + OH --> ANO2                                                                      ', &
     '            MGLY + OH --> XO2 + C2O3                                                                ', &
     '           MGLY + NO3 --> HNO3 + CO + C2O3                                                          ', &
     '            C2H4 + O3 --> 6.95319e-31 HCOOH + 6.95319e-31 CO + HCHO + 6.95319e-31 OH + 6.95319e-31 H', &
     '            C2H4 + OH --> 6.95319e-31 HCHO + XO2 + 6.95319e-31 ALD2 + HO2                           ', &
     '            OLET + O3 --> 6.95319e-31 HCOOH + 6.95319e-31 RCOOH + 6.95319e-31 CH4 + 6.95319e-31 C2H6', &
     '            OLEI + O3 --> 6.95319e-31 RCOOH + 6.95319e-31 CH4 + 6.95319e-31 C2H6 + 6.95319e-31 XPAR ', &
     '            OLET + OH --> XPAR + HCHO + XO2 + ALD2 + HO2                                            ', &
     '            OLEI + OH --> 6.95319e-31 XPAR + XO2 + 6.95319e-31 AONE + 6.95319e-31 ALD2 + HO2        ', &
     '           OLET + NO3 --> NAP                                                                       ', &
     '           OLEI + NO3 --> NAP                                                                       ', &
     '             TOL + OH --> 6.95319e-31 TO2 + 6.95319e-31 CRES + 6.95319e-31 XO2 + 6.95319e-31 HO2    ', &
     '             XYL + OH --> 6.95319e-31 TO2 + 6.95319e-31 CRES + 6.95319e-31 PAR + 6.95319e-31 XO2 + 6', &
     '             TO2 + NO --> 6.95319e-31 OPEN + 6.95319e-31 ONIT + 6.95319e-31 NO2 + 6.95319e-31 HO2   ', &
     '            CRES + OH --> 6.95319e-31 CRO + 6.95319e-31 OPEN + 6.95319e-31 XO2 + 6.95319e-31 HO2    ', &
     '           CRES + NO3 --> CRO + HNO3                                                                ', &
     '            CRO + NO2 --> ONIT                                                                      ', &
     '            OPEN + OH --> 6.95319e-31 CO + HCHO + XO2 + C2O3 + 6.95319e-31 HO2                      ', &
     '            OPEN + O3 --> 6.95319e-31 CO + 6.95319e-31 HCHO + 6.95319e-31 XO2 + 6.95319e-31 MGLY + 6', &
     '            ISOP + OH --> ISOPP + 6.95319e-31 XO2                                                   ', &
     '            ISOP + O3 --> 6.95319e-31 RCOOH + 6.95319e-31 CO + 6.95319e-31 HCHO + 6.95319e-31 XO2 + ', &
     '           ISOP + NO3 --> ISOPN                                                                     ', &
     '          ISOPRD + OH --> 6.95319e-31 ISOPO2 + 6.95319e-31 XO2 + 6.95319e-31 C2O3                   ', &
     '          ISOPRD + O3 --> 6.95319e-31 RCOOH + 6.95319e-31 CO + 6.95319e-31 HCHO + 6.95319e-31 XO2 + ', &
     '         ISOPRD + NO3 --> 6.95319e-31 HNO3 + 6.95319e-31 CO + 6.95319e-31 PAR + 6.95319e-31 HCHO + 6', &
     '           ISOPP + NO --> 6.95319e-31 PAR + 6.95319e-31 HCHO + 6.95319e-31 ISOPRD + 6.95319e-31 ONIT', &
     '           ISOPN + NO --> 6.95319e-31 PAR + 6.95319e-31 ALD2 + 6.95319e-31 ISOPRD + 6.95319e-31 ONIT', &
     '          ISOPO2 + NO --> 6.95319e-31 CO + 6.95319e-31 HCHO + 6.95319e-31 AONE + 6.95319e-31 MGLY + ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '          ISOPP + HO2 --> ROOH                                                                      ', &
     '          ISOPN + HO2 --> 6.95319e-31 PAR + ONIT                                                    ', &
     '         ISOPO2 + HO2 --> ROOH                                                                      ', &
     '          CH3OOH + OH --> 6.95319e-31 HCHO + 6.95319e-31 CH3O2 + 6.95319e-31 OH                     ', &
     '          ETHOOH + OH --> 6.95319e-31 ETHP + 6.95319e-31 ALD2 + 6.95319e-31 OH                      ', &
     '            ROOH + OH --> 6.95319e-31 XPAR + 6.95319e-31 MGLY + 6.95319e-31 ALD2 + 6.95319e-31 RO2 +', &
     '            ONIT + OH --> NAP                                                                       ', &
     '           NO2 + C2O3 --> PAN                                                                       ', &
     '                  PAN --> NO2 + C2O3                                                                ', &
     '           CH3OH + OH --> HCHO + HO2                                                                ', &
     '           CH3O2 + NO --> HCHO + NO2 + HO2                                                          ', &
     '            ETHP + NO --> ALD2 + NO2 + HO2                                                          ', &
     '             RO2 + NO --> 6.95319e-31 XPAR + 6.95319e-31 XO2 + 6.95319e-31 AONE + 6.95319e-31 ETHP +', &
     '            C2O3 + NO --> CH3O2 + NO2                                                               ', &
     '            ANO2 + NO --> HCHO + NO2 + C2O3                                                         ', &
     '             NAP + NO --> XPAR + 6.95319e-31 HCHO + 6.95319e-31 ALD2 + 6.95319e-31 ONIT + 6.95319e-3', &
     '             XO2 + NO --> NO2                                                                       ', &
     '          CH3O2 + NO3 --> HCHO + NO2 + HO2                                                          ', &
     '           ETHP + NO3 --> ALD2 + NO2 + HO2                                                          ', &
     '            RO2 + NO3 --> 6.95319e-31 XPAR + 6.95319e-31 XO2 + 6.95319e-31 AONE + 6.95319e-31 ETHP +', &
     '           C2O3 + NO3 --> CH3O2 + NO2                                                               ', &
     '           ANO2 + NO3 --> HCHO + NO2 + C2O3                                                         ', &
     '            NAP + NO3 --> XPAR + 6.95319e-31 HCHO + 6.95319e-31 ALD2 + 6.95319e-31 ONIT + 6.95319e-3', &
     '            XO2 + NO3 --> NO2                                                                       ', &
     '          CH3O2 + HO2 --> CH3OOH                                                                    ', &
     '           ETHP + HO2 --> ETHOOH                                                                    ', &
     '            RO2 + HO2 --> ROOH                                                                      ', &
     '           C2O3 + HO2 --> 6.95319e-31 RCOOH + 6.95319e-31 O3                                        ', &
     '           ANO2 + HO2 --> ROOH                                                                      ', &
     '            NAP + HO2 --> ONIT                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(16) :: EQN_NAMES_4 = (/ &
     '            XO2 + HO2 -->                                                                           ', &
     '            ANOL + OH --> ALD2 + HO2                                                                ', &
     '           XPAR + PAR -->                                                                           ', &
     '                  HCl --> HCl                                                                       ', &
     '                  NH3 --> NH3                                                                       ', &
     '                H2SO4 --> H2SO4                                                                     ', &
     '                CH3O2 --> 6.95319e-31 CH3OH + 6.95319e-31 HCHO + 6.95319e-31 HO2                    ', &
     '                 ETHP --> 6.95319e-31 C2H6 + 6.95319e-31 ALD2 + 6.95319e-31 HO2                     ', &
     '                  RO2 --> 6.95319e-31 XPAR + 6.95319e-31 XO2 + 6.95319e-31 AONE + 6.95319e-31 ETHP +', &
     '                 C2O3 --> CH3O2                                                                     ', &
     '                 ANO2 --> 6.95319e-31 HCHO + 6.95319e-31 AONE + 6.95319e-31 MGLY + 6.95319e-31 C2O3 ', &
     '                  NAP --> XPAR + 6.95319e-31 HCHO + 6.95319e-31 ALD2 + 6.95319e-31 ONIT + 6.95319e-3', &
     '                ISOPP --> ISOPRD                                                                    ', &
     '                ISOPN --> 6.95319e-31 PAR + ALD2 + ONIT                                             ', &
     '               ISOPO2 --> 6.95319e-31 AONE + 6.95319e-31 ALD2                                       ', &
     '                  XO2 -->                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(136) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4 /)

! INLINED global variables

! End INLINED global variables


END MODULE cbmz_bb_Monitor
