! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cb05_sorg_vbs_aq_Monitor.f90
! Time                 : Mon Sep 26 23:36:52 2022
! Working directory    : /home/ess/xiaodong/WORK/WRFCHEM/model/WRF4.4/chem/KPP/mechanisms/cb05_sorg_vbs_aq
! Equation file        : cb05_sorg_vbs_aq.kpp
! Output root filename : cb05_sorg_vbs_aq
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cb05_sorg_vbs_aq_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'tolaer1     ','tolaer2     ','cslaer      ', &
     'xylaer1     ','xylaer2     ','isoaer1     ', &
     'isoaer2     ','sulf        ','sulaer      ', &
     'terpaer     ','humaer      ','hum         ', &
     'limaer1     ','limaer2     ','lim         ', &
     'ociaer1     ','ociaer2     ','oci         ', &
     'apinaer1    ','apinaer2    ','apinaer3    ', &
     'apinaer4    ','apin        ','bpinaer1    ', &
     'bpinaer2    ','bpinaer3    ','bpinaer4    ', &
     'bpinaer5    ','bpin        ','teraer1     ', &
     'teraer2     ','ter         ','alkhaer1    ', &
     'alkh        ','pahaer1     ','pahaer2     ', &
     'pah         ','hg2         ','CVASOA1     ', &
     'CVASOA2     ','CVASOA3     ','CVASOA4     ', &
     'CVBSOA1     ','CVBSOA2     ','CVBSOA3     ', &
     'CVBSOA4     ','cl2         ','so2         ', &
     'pan         ','hocl        ','tol         ', &
     'h2          ','o1d         ','n2o5        ', &
     'xyl         ','ch4         ','hg0         ', &
     'hono        ','facd        ','to2         ', &
     'pacd        ','aacd        ','panx        ', &
     'pna         ','etha        ','meoh        ', &
     'etoh        ','h2o2        ','hco3        ', &
     'hcl         ','cro         ','rooh        ', &
     'clo         ','mgly        ','fmcl        ', &
     'mepx        ','hno3        ','co          ', &
     'open        ','ror         ','eth         ', &
     'cres        ','terp        ','iole        ', &
     'ole         ','xo2n        ','par         ', &
     'isop        ','ispd        ','aldx        ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(17) :: SPC_NAMES_1 = (/ &
     'ald2        ','form        ','ntr         ', &
     'o3          ','no3         ','xo2         ', &
     'c2o3        ','oh          ','no          ', &
     'cl          ','o           ','ho2         ', &
     'cxo3        ','meo2        ','no2         ', &
     'H2O         ','M           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(107) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '                   no2 --> no + o                                                                   ', &
     '                     o --> o3                                                                       ', &
     '               o3 + no --> no2                                                                      ', &
     '               o + no2 --> no                                                                       ', &
     '               o + no2 --> no3                                                                      ', &
     '                no + o --> no2                                                                      ', &
     '              o3 + no2 --> no3                                                                      ', &
     '                    o3 --> o                                                                        ', &
     '                    o3 --> o1d                                                                      ', &
     '               o1d + M --> o + M                                                                    ', &
     '             o1d + H2O --> 6.95286e-31 oh                                                           ', &
     '               o3 + oh --> ho2                                                                      ', &
     '              o3 + ho2 --> oh                                                                       ', &
     '                   no3 --> o + no2                                                                  ', &
     '                   no3 --> no                                                                       ', &
     '              no3 + no --> 6.95286e-31 no2                                                          ', &
     '             no3 + no2 --> no + no2                                                                 ', &
     '             no3 + no2 --> n2o5                                                                     ', &
     '            n2o5 + H2O --> 6.95286e-31 hno3                                                         ', &
     'n2o5 + 6.95286e-31 H2O --> 6.95286e-31 hno3                                                         ', &
     '                  n2o5 --> no3 + no2                                                                ', &
     '        6.95286e-31 no --> 6.95286e-31 no2                                                          ', &
     '        no + no2 + H2O --> 6.95286e-31 hono                                                         ', &
     '               oh + no --> hono                                                                     ', &
     '                  hono --> oh + no                                                                  ', &
     '             hono + oh --> no2                                                                      ', &
     '      6.95286e-31 hono --> no + no2                                                                 ', &
     '              oh + no2 --> hno3                                                                     ', &
     '             hno3 + oh --> no3                                                                      ', &
     '              no + ho2 --> oh + no2                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '             ho2 + no2 --> pna                                                                      ', &
     '                   pna --> ho2 + no2                                                                ', &
     '              pna + oh --> no2                                                                      ', &
     '       6.95286e-31 ho2 --> h2o2                                                                     ', &
     ' 6.95286e-31 ho2 + H2O --> h2o2                                                                     ', &
     '                  h2o2 --> 6.95286e-31 oh                                                           ', &
     '             h2o2 + oh --> ho2                                                                      ', &
     '              h2 + o1d --> oh + ho2                                                                 ', &
     '               h2 + oh --> ho2                                                                      ', &
     '                oh + o --> ho2                                                                      ', &
     '        6.95286e-31 oh --> o                                                                        ', &
     '        6.95286e-31 oh --> h2o2                                                                     ', &
     '              oh + ho2 --> H2O                                                                      ', &
     '               o + ho2 --> oh                                                                       ', &
     '              h2o2 + o --> oh + ho2                                                                 ', &
     '               no3 + o --> no2                                                                      ', &
     '              no3 + oh --> ho2 + no2                                                                ', &
     '             no3 + ho2 --> hno3                                                                     ', &
     '              o3 + no3 --> no2                                                                      ', &
     '       6.95286e-31 no3 --> 6.95286e-31 no2                                                          ', &
     '                   pna --> 6.95286e-31 no3 + 6.95286e-31 oh + 6.95286e-31 ho2 + 6.95286e-31 no2     ', &
     '                  hno3 --> oh + no2                                                                 ', &
     '                  n2o5 --> no3 + no2                                                                ', &
     '              xo2 + no --> no2                                                                      ', &
     '             xo2n + no --> ntr                                                                      ', &
     '             xo2 + ho2 --> rooh                                                                     ', &
     '            xo2n + ho2 --> rooh                                                                     ', &
     '       6.95286e-31 xo2 --> 6.95286e-31 M                                                            ', &
     '      6.95286e-31 xo2n --> 6.95286e-31 M                                                            ', &
     '            xo2n + xo2 --> 6.95286e-31 M                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '              ntr + oh --> hno3 - 6.95286e-31 par + 6.95286e-31 aldx + 6.95286e-31 ald2 + 6.95286e-3', &
     '                   ntr --> - 6.95286e-31 par + 6.95286e-31 aldx + 6.95286e-31 ald2 + 6.95286e-31 for', &
     '             rooh + oh --> 6.95286e-31 aldx + 6.95286e-31 ald2 + xo2                                ', &
     '                  rooh --> 6.95286e-31 aldx + 6.95286e-31 ald2 + oh + ho2                           ', &
     '               co + oh --> ho2                                                                      ', &
     '              ch4 + oh --> meo2                                                                     ', &
     '             no + meo2 --> form + ho2 + no2                                                         ', &
     '            ho2 + meo2 --> mepx                                                                     ', &
     '      6.95286e-31 meo2 --> 6.95286e-31 meoh + 6.95286e-31 form + 6.95286e-31 ho2                    ', &
     '             mepx + oh --> 6.95286e-31 xo2 + 6.95286e-31 ho2 + 6.95286e-31 meo2                     ', &
     '                  mepx --> form + oh + ho2                                                          ', &
     '             meoh + oh --> form + ho2                                                               ', &
     '             form + oh --> co + ho2                                                                 ', &
     '                  form --> co + 6.95286e-31 ho2                                                     ', &
     '                  form --> co                                                                       ', &
     '              form + o --> co + oh + ho2                                                            ', &
     '            form + no3 --> hno3 + co + ho2                                                          ', &
     '            form + ho2 --> hco3                                                                     ', &
     '                  hco3 --> form + ho2                                                               ', &
     '             hco3 + no --> facd + ho2 + no2                                                         ', &
     '            hco3 + ho2 --> mepx                                                                     ', &
     '             facd + oh --> ho2                                                                      ', &
     '              ald2 + o --> c2o3 + oh                                                                ', &
     '             ald2 + oh --> c2o3                                                                     ', &
     '            ald2 + no3 --> hno3 + c2o3                                                              ', &
     '                  ald2 --> co + ho2 + meo2                                                          ', &
     '             c2o3 + no --> meo2 + no2                                                               ', &
     '            c2o3 + no2 --> pan                                                                      ', &
     '                   pan --> c2o3 + no2                                                               ', &
     '                   pan --> c2o3 + no2                                                               ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '            c2o3 + ho2 --> 6.95286e-31 pacd + 6.95286e-31 aacd + 6.95286e-31 o3                     ', &
     '           c2o3 + meo2 --> 6.95286e-31 aacd + form + 6.95286e-31 ho2 + 6.95286e-31 meo2             ', &
     '            xo2 + c2o3 --> 6.95286e-31 aacd + 6.95286e-31 meo2                                      ', &
     '      6.95286e-31 c2o3 --> 6.95286e-31 meo2                                                         ', &
     '             pacd + oh --> c2o3                                                                     ', &
     '                  pacd --> oh + meo2                                                                ', &
     '             aacd + oh --> meo2                                                                     ', &
     '              aldx + o --> oh + cxo3                                                                ', &
     '             aldx + oh --> cxo3                                                                     ', &
     '            aldx + no3 --> hno3 + cxo3                                                              ', &
     '                  aldx --> co + ho2 + meo2                                                          ', &
     '             no + cxo3 --> ald2 + xo2 + ho2 + no2                                                   ', &
     '            cxo3 + no2 --> panx                                                                     ', &
     '                  panx --> cxo3 + no2                                                               ', &
     '                  panx --> cxo3 + no2                                                               ', &
     '             panx + oh --> ald2 + no2                                                               ', &
     '            ho2 + cxo3 --> 6.95286e-31 pacd + 6.95286e-31 aacd + 6.95286e-31 o3                     ', &
     '           cxo3 + meo2 --> 6.95286e-31 aacd + 6.95286e-31 ald2 + 6.95286e-31 form + 6.95286e-31 xo2 ', &
     '            xo2 + cxo3 --> 6.95286e-31 aacd + 6.95286e-31 ald2                                      ', &
     '      6.95286e-31 cxo3 --> 6.95286e-31 ald2 + 6.95286e-31 xo2 + 6.95286e-31 ho2                     ', &
     '           c2o3 + cxo3 --> ald2 + xo2 + ho2 + meo2                                                  ', &
     '              par + oh --> 6.95286e-31 ror + 6.95286e-31 xo2n - 6.95286e-31 par + 6.95286e-31 aldx +', &
     '                   ror --> 6.95286e-31 ror + 6.95286e-31 xo2n - 6.95286e-31 par + 6.95286e-31 aldx +', &
     '                   ror --> ho2                                                                      ', &
     '             ror + no2 --> ntr                                                                      ', &
     '               ole + o --> 6.95286e-31 co + 6.95286e-31 xo2n + 6.95286e-31 par + 6.95286e-31 aldx + ', &
     '              ole + oh --> - 6.95286e-31 par + 6.95286e-31 aldx + 6.95286e-31 ald2 + 6.95286e-31 for', &
     '              ole + o3 --> 6.95286e-31 co - par + 6.95286e-31 aldx + 6.95286e-31 ald2 + 6.95286e-31 ', &
     '             ole + no3 --> 6.95286e-31 xo2n - par + 6.95286e-31 aldx + 6.95286e-31 ald2 + form + 6.9', &
     '               eth + o --> co + form + 6.95286e-31 xo2 + 6.95286e-31 oh + 6.95286e-31 ho2           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '              eth + oh --> 6.95286e-31 aldx + 6.95286e-31 form + xo2 + ho2                          ', &
     '              eth + o3 --> 6.95286e-31 facd + 6.95286e-31 co + form + 6.95286e-31 oh + 6.95286e-31 h', &
     '             eth + no3 --> 6.95286e-31 form + xo2 + no2                                             ', &
     '              iole + o --> 6.95286e-31 co + 6.95286e-31 par + 6.95286e-31 aldx + 6.95286e-31 ald2 + ', &
     '             iole + oh --> 6.95286e-31 aldx + 6.95286e-31 ald2 + xo2 + ho2                          ', &
     '             iole + o3 --> 6.95286e-31 co + 6.95286e-31 aldx + 6.95286e-31 ald2 + 6.95286e-31 form +', &
     '            iole + no3 --> 6.95286e-31 aldx + 6.95286e-31 ald2 + ho2 + no2                          ', &
     '              tol + oh --> 6.95286e-31 tolaer1 + 6.95286e-31 tolaer2 + 6.95286e-31 to2 + 6.95286e-31', &
     '              to2 + no --> 6.95286e-31 open + 6.95286e-31 ntr + 6.95286e-31 ho2 + 6.95286e-31 no2   ', &
     '                   to2 --> cres + ho2                                                               ', &
     '             cres + oh --> cslaer + 6.95286e-31 cro + 6.95286e-31 open + 6.95286e-31 xo2 + 6.95286e-', &
     '            cres + no3 --> cslaer + cro + hno3                                                      ', &
     '             cro + no2 --> ntr                                                                      ', &
     '             cro + ho2 --> cres                                                                     ', &
     '                  open --> co + c2o3 + ho2                                                          ', &
     '             open + oh --> 6.95286e-31 co + form + xo2 + c2o3 + 6.95286e-31 ho2                     ', &
     '             open + o3 --> 6.95286e-31 mgly + 6.95286e-31 co + 6.95286e-31 aldx + 6.95286e-31 form +', &
     '              xyl + oh --> 6.95286e-31 xylaer1 + 6.95286e-31 xylaer2 + 6.95286e-31 to2 + 6.95286e-31', &
     '             mgly + oh --> xo2 + c2o3                                                               ', &
     '                  mgly --> co + c2o3 + ho2                                                          ', &
     '              isop + o --> 6.95286e-31 isoaer1 + 6.95286e-31 isoaer2 + 6.95286e-31 ispd + 6.95286e-3', &
     '             isop + oh --> 6.95286e-31 isoaer1 + 6.95286e-31 isoaer2 + 6.95286e-31 xo2n + 6.95286e-3', &
     '             isop + o3 --> 6.95286e-31 isoaer1 + 6.95286e-31 isoaer2 + 6.95286e-31 co + 6.95286e-31 ', &
     '            isop + no3 --> 6.95286e-31 isoaer1 + 6.95286e-31 isoaer2 + 6.95286e-31 ispd + 6.95286e-3', &
     '             ispd + oh --> 6.95286e-31 mgly + 6.95286e-31 co + 6.95286e-31 par + 6.95286e-31 aldx + ', &
     '             ispd + o3 --> 6.95286e-31 mgly + 6.95286e-31 co + 6.95286e-31 par + 6.95286e-31 ald2 + ', &
     '            ispd + no3 --> 6.95286e-31 hno3 + 6.95286e-31 co + 6.95286e-31 par + 6.95286e-31 aldx + ', &
     '                  ispd --> 6.95286e-31 co + 6.95286e-31 par + 6.95286e-31 ald2 + 6.95286e-31 form + ', &
     '              terp + o --> terpaer + 6.95286e-31 par + 6.95286e-31 oh                               ', &
     '             terp + oh --> terpaer + 6.95286e-31 xo2n + 6.95286e-31 par + 6.95286e-31 aldx + 6.95286' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '             terp + o3 --> terpaer + 6.95286e-31 co + 6.95286e-31 xo2n + 6.95286e-31 par + 6.95286e-', &
     '            terp + no3 --> terpaer + 6.95286e-31 xo2n + 6.95286e-31 aldx + 6.95286e-31 ntr + 6.95286', &
     '              so2 + oh --> sulf + sulaer + ho2                                                      ', &
     '             etoh + oh --> 6.95286e-31 aldx + 6.95286e-31 ald2 + 6.95286e-31 form + 6.95286e-31 xo2 ', &
     '             etha + oh --> 6.95286e-31 xo2n + 6.95286e-31 ald2 + 6.95286e-31 xo2 + ho2              ', &
     '            isop + no2 --> 6.95286e-31 par + 6.95286e-31 ispd + 6.95286e-31 aldx + 6.95286e-31 ntr +', &
     '                   cl2 --> 6.95286e-31 cl                                                           ', &
     '                  hocl --> oh + cl                                                                  ', &
     '               o3 + cl --> clo                                                                      ', &
     '       6.95286e-31 clo --> 6.95286e-31 cl2 + 6.95286e-31 cl                                         ', &
     '              clo + no --> cl + no2                                                                 ', &
     '             clo + ho2 --> hocl                                                                     ', &
     '             fmcl + oh --> co + cl                                                                  ', &
     '                  fmcl --> co + cl + ho2                                                            ', &
     '              ch4 + cl --> hcl + meo2                                                               ', &
     '              par + cl --> hcl + 6.95286e-31 ror + 6.95286e-31 xo2n - 6.95286e-31 par + 6.95286e-31 ', &
     '             etha + cl --> hcl + 6.95286e-31 xo2n + 6.95286e-31 ald2 + 6.95286e-31 xo2 + ho2        ', &
     '              eth + cl --> fmcl + form + 6.95286e-31 xo2 + ho2                                      ', &
     '              ole + cl --> fmcl - par + 6.95286e-31 aldx + 6.95286e-31 ald2 + 6.95286e-31 xo2 + ho2 ', &
     '             iole + cl --> 6.95286e-31 hcl + 6.95286e-31 fmcl + 6.95286e-31 ole + 6.95286e-31 par + ', &
     '             isop + cl --> 6.95286e-31 hcl + 6.95286e-31 fmcl + ispd + xo2 + ho2                    ', &
     '             form + cl --> hcl + co + ho2                                                           ', &
     '             ald2 + cl --> hcl + c2o3                                                               ', &
     '             aldx + cl --> hcl + cxo3                                                               ', &
     '             meoh + cl --> hcl + form + ho2                                                         ', &
     '             etoh + cl --> hcl + ald2 + ho2                                                         ', &
     '              hcl + oh --> cl                                                                       ', &
     '              hg0 + o3 --> hg2                                                                      ', &
     '              hg0 + oh --> hg2                                                                      ', &
     '            hg0 + h2o2 --> hg2                                                                      ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(18) :: EQN_NAMES_6 = (/ &
     '              hum + oh --> humaer + oh                                                              ', &
     '              lim + oh --> 6.95286e-31 limaer1 + 6.95286e-31 limaer2 + oh                           ', &
     '              oci + oh --> 6.95286e-31 ociaer1 + 6.95286e-31 ociaer2 + oh                           ', &
     '             apin + oh --> 6.95286e-31 apinaer1 + 6.95286e-31 apinaer2 + oh                         ', &
     '             apin + o3 --> 6.95286e-31 apinaer3 + 6.95286e-31 apinaer4 + o3                         ', &
     '             bpin + oh --> 6.95286e-31 bpinaer1 + 6.95286e-31 bpinaer2 + oh                         ', &
     '             bpin + o3 --> 6.95286e-31 bpinaer3 + 6.95286e-31 bpinaer4 + o3                         ', &
     '            bpin + no3 --> bpinaer5 + no3                                                           ', &
     '              ter + oh --> 6.95286e-31 teraer1 + 6.95286e-31 teraer2 + oh                           ', &
     '             alkh + oh --> 6.95286e-31 alkhaer1 + oh                                                ', &
     '              pah + oh --> 6.95286e-31 pahaer1 + 6.95286e-31 pahaer2 + oh                           ', &
     '          CVASOA4 + oh --> 6.95286e-31 CVASOA3 + oh                                                 ', &
     '          CVASOA3 + oh --> 6.95286e-31 CVASOA2 + oh                                                 ', &
     '          CVASOA2 + oh --> 6.95286e-31 CVASOA1 + oh                                                 ', &
     '          CVBSOA4 + oh --> 6.95286e-31 CVBSOA3 + oh                                                 ', &
     '          CVBSOA3 + oh --> 6.95286e-31 CVBSOA2 + oh                                                 ', &
     '          CVBSOA2 + oh --> 6.95286e-31 CVBSOA1 + oh                                                 ', &
     '                   so2 --> sulf                                                                     ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(198) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6 /)

! INLINED global variables

! End INLINED global variables


END MODULE cb05_sorg_vbs_aq_Monitor
